// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
// Task: 实现语音识别服务基础架构

library;

import 'package:speech_to_text/speech_to_text.dart';
import 'package:speech_to_text/speech_recognition_result.dart';
import 'package:speech_to_text/speech_recognition_error.dart';

/// 语音识别服务
/// 
/// 负责语音转文字功能，支持：
/// - 语音识别初始化
/// - 开始/停止监听
/// - 权限管理
/// - 多语言支持（中文/英文/日文）
/// 
/// 注意：需要添加依赖 speech_to_text: ^6.3.0

/// 语音识别状态
enum VoiceRecognitionStatus {
  /// 未初始化
  notInitialized,
  
  /// 就绪
  ready,
  
  /// 监听中
  listening,
  
  /// 处理中
  processing,
  
  /// 错误
  error,
}

/// 语音识别结果
class VoiceRecognitionResult {
  /// 识别文本
  final String text;
  
  /// 置信度 (0.0-1.0)
  final double confidence;
  
  /// 是否为最终结果
  final bool isFinal;
  
  /// 时间戳
  final DateTime timestamp;

  const VoiceRecognitionResult({
    required this.text,
    required this.confidence,
    required this.isFinal,
    required this.timestamp,
  });

  factory VoiceRecognitionResult.empty() {
    return VoiceRecognitionResult(
      text: '',
      confidence: 0.0,
      isFinal: false,
      timestamp: DateTime.now(),
    );
  }

  @override
  String toString() {
    return 'VoiceRecognitionResult(text: $text, confidence: $confidence, isFinal: $isFinal)';
  }
}

/// 语音识别服务
/// 
/// 使用 speech_to_text 实现语音转文字功能
class VoiceRecognitionService {
  static final VoiceRecognitionService _instance = VoiceRecognitionService._internal();
  factory VoiceRecognitionService() => _instance;
  VoiceRecognitionService._internal();

  // 当前状态
  VoiceRecognitionStatus _status = VoiceRecognitionStatus.notInitialized;
  
  // 当前语言
  String _locale = 'zh-CN';
  
  // 回调函数
  Function(VoiceRecognitionResult)? _onResult;
  Function(String)? _onError;
  
  // 语音识别引擎
  final SpeechToText _speech = SpeechToText();
  
  /// 获取当前状态
  VoiceRecognitionStatus get status => _status;
  
  /// 是否正在监听
  bool get isListening => _status == VoiceRecognitionStatus.listening;

  /// 初始化语音识别
  /// 
  /// 返回是否初始化成功
  Future<bool> initialize() async {
    if (_status == VoiceRecognitionStatus.ready) {
      return true;
    }

    try {
      // 初始化语音识别引擎
      bool available = await _speech.initialize(
        onError: (SpeechRecognitionError error) {
          print('[VoiceRecognitionService] 识别错误: ${error.errorMsg}');
          _onError?.call(error.errorMsg);
          _status = VoiceRecognitionStatus.error;
        },
        onStatus: (String status) {
          print('[VoiceRecognitionService] 状态变化: $status');
          _handleStatus(status);
        },
      );
      
      if (available) {
        _status = VoiceRecognitionStatus.ready;
        print('[VoiceRecognitionService] 初始化成功');
        return true;
      } else {
        print('[VoiceRecognitionService] 语音识别不可用');
        _status = VoiceRecognitionStatus.error;
        return false;
      }
    } catch (e) {
      print('[VoiceRecognitionService] 初始化失败: $e');
      _status = VoiceRecognitionStatus.error;
      return false;
    }
  }

  /// 开始监听
  /// 
  /// [onResult] 识别结果回调
  /// [onError] 错误回调
  Future<void> startListening({
    required Function(VoiceRecognitionResult) onResult,
    required Function(String) onError,
  }) async {
    if (_status != VoiceRecognitionStatus.ready) {
      onError('服务未就绪，请先调用 initialize()');
      return;
    }

    _onResult = onResult;
    _onError = onError;

    try {
      // 开始监听语音输入
      await _speech.listen(
        onResult: (SpeechRecognitionResult result) {
          final voiceResult = VoiceRecognitionResult(
            text: result.recognizedWords,
            confidence: result.confidence,
            isFinal: result.finalResult,
            timestamp: DateTime.now(),
          );
          
          print('[VoiceRecognitionService] 识别结果: ${result.recognizedWords} (置信度: ${result.confidence})');
          _onResult?.call(voiceResult);
          
          // 如果是最终结果，自动停止监听
          if (result.finalResult) {
            _status = VoiceRecognitionStatus.processing;
          }
        },
        localeId: _locale,
        listenOptions: SpeechListenOptions(
          listenMode: ListenMode.confirmation,
          cancelOnError: true,
          partialResults: true,
        ),
      );
      
      _status = VoiceRecognitionStatus.listening;
      print('[VoiceRecognitionService] 开始监听（语言: $_locale）');
    } catch (e) {
      _status = VoiceRecognitionStatus.error;
      _onError?.call('开始监听失败: $e');
    }
  }

  /// 停止监听
  Future<void> stopListening() async {
    if (_status != VoiceRecognitionStatus.listening) {
      return;
    }

    try {
      // 停止监听
      await _speech.stop();
      
      _status = VoiceRecognitionStatus.ready;
      print('[VoiceRecognitionService] 停止监听');
    } catch (e) {
      _onError?.call('停止监听失败: $e');
    }
  }

  /// 取消监听
  Future<void> cancel() async {
    if (_status != VoiceRecognitionStatus.listening) {
      return;
    }

    try {
      // 取消监听
      await _speech.cancel();
      
      _status = VoiceRecognitionStatus.ready;
      print('[VoiceRecognitionService] 取消监听');
    } catch (e) {
      _onError?.call('取消监听失败: $e');
    }
  }

  /// 检查权限
  Future<bool> hasPermission() async {
    bool hasPermission = await _speech.hasPermission;
    print('[VoiceRecognitionService] 权限检查: $hasPermission');
    return hasPermission;
  }

  /// 设置语言
  /// 
  /// [locale] 语言代码
  /// - zh-CN: 中文（简体）
  /// - en-US: 英文（美国）
  /// - ja-JP: 日文
  void setLocale(String locale) {
    if (_status == VoiceRecognitionStatus.listening) {
      print('[VoiceRecognitionService] 警告：监听中不能切换语言');
      return;
    }
    
    _locale = locale;
    print('[VoiceRecognitionService] 切换语言: $locale');
  }

  /// 获取支持的语言列表
  Future<List<String>> getAvailableLocales() async {
    List<LocaleName> locales = await _speech.locales();
    List<String> localeIds = locales.map((locale) => locale.localeId).toList();
    print('[VoiceRecognitionService] 支持的语言: ${localeIds.length} 种');
    return localeIds;
  }
  
  /// 处理状态变化
  void _handleStatus(String status) {
    switch (status) {
      case 'listening':
        _status = VoiceRecognitionStatus.listening;
        break;
      case 'notListening':
        if (_status != VoiceRecognitionStatus.error) {
          _status = VoiceRecognitionStatus.ready;
        }
        break;
      case 'done':
        _status = VoiceRecognitionStatus.ready;
        break;
      default:
        print('[VoiceRecognitionService] 未知状态: $status');
    }
  }

  /// 释放资源
  Future<void> dispose() async {
    await stopListening();
    _onResult = null;
    _onError = null;
    print('[VoiceRecognitionService] 资源已释放');
  }
}
