// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
// Task: 实现语音合成服务基础架构

library;

import 'package:flutter_tts/flutter_tts.dart';

/// 语音合成服务
/// 
/// 负责文字转语音功能，支持：
/// - 语音播报
/// - 音量/语速/音调控制
/// - 队列管理
/// - 多语言支持
/// 
/// 注意：需要添加依赖 flutter_tts: ^3.8.0

/// 语音合成状态
enum VoiceSynthesisStatus {
  /// 未初始化
  notInitialized,
  
  /// 就绪
  ready,
  
  /// 播放中
  playing,
  
  /// 暂停
  paused,
  
  /// 错误
  error,
}

/// 语音合成服务
/// 
/// 使用 flutter_tts 实现文字转语音功能
class VoiceSynthesisService {
  static final VoiceSynthesisService _instance = VoiceSynthesisService._internal();
  factory VoiceSynthesisService() => _instance;
  VoiceSynthesisService._internal();

  // 当前状态
  VoiceSynthesisStatus _status = VoiceSynthesisStatus.notInitialized;
  
  // 当前语言
  String _language = 'zh-CN';
  
  // 音频参数
  double _volume = 1.0;   // 音量 0.0-1.0
  double _pitch = 1.0;    // 音调 0.5-2.0
  double _rate = 0.5;     // 语速 0.0-1.0
  
  // 播报队列
  final List<String> _queue = [];
  bool _isProcessingQueue = false;
  
  // 语音合成引擎
  final FlutterTts _tts = FlutterTts();
  
  /// 获取当前状态
  VoiceSynthesisStatus get status => _status;
  
  /// 是否正在播放
  bool get isPlaying => _status == VoiceSynthesisStatus.playing;

  /// 初始化语音合成
  Future<void> initialize() async {
    if (_status == VoiceSynthesisStatus.ready) {
      return;
    }

    try {
      // 设置语言
      await _tts.setLanguage(_language);
      
      // 设置音频参数
      await _tts.setVolume(_volume);
      await _tts.setPitch(_pitch);
      await _tts.setSpeechRate(_rate);
      
      // 设置回调
      _tts.setStartHandler(() {
        _status = VoiceSynthesisStatus.playing;
        print('[VoiceSynthesisService] 开始播报');
      });
      
      _tts.setCompletionHandler(() {
        _status = VoiceSynthesisStatus.ready;
        print('[VoiceSynthesisService] 播报完成');
        _processNextInQueue();
      });
      
      _tts.setErrorHandler((msg) {
        _status = VoiceSynthesisStatus.error;
        print('[VoiceSynthesisService] 错误: $msg');
      });
      
      _tts.setCancelHandler(() {
        _status = VoiceSynthesisStatus.ready;
        print('[VoiceSynthesisService] 取消播报');
      });
      
      _tts.setPauseHandler(() {
        _status = VoiceSynthesisStatus.paused;
        print('[VoiceSynthesisService] 暂停播报');
      });
      
      _tts.setContinueHandler(() {
        _status = VoiceSynthesisStatus.playing;
        print('[VoiceSynthesisService] 继续播报');
      });
      
      print('[VoiceSynthesisService] 初始化成功');
      _status = VoiceSynthesisStatus.ready;
    } catch (e) {
      print('[VoiceSynthesisService] 初始化失败: $e');
      _status = VoiceSynthesisStatus.error;
    }
  }

  /// 播报文本
  /// 
  /// [text] 要播报的文本
  /// [volume] 音量 (0.0-1.0)
  /// [pitch] 音调 (0.5-2.0)
  /// [rate] 语速 (0.0-1.0)
  Future<void> speak(
    String text, {
    double? volume,
    double? pitch,
    double? rate,
  }) async {
    if (_status == VoiceSynthesisStatus.notInitialized) {
      await initialize();
    }

    if (text.isEmpty) {
      return;
    }

    try {
      // 设置参数（如果提供）
      if (volume != null) await setVolume(volume);
      if (pitch != null) await setPitch(pitch);
      if (rate != null) await setSpeechRate(rate);

      // 播报文本
      await _tts.speak(text);
      
      print('[VoiceSynthesisService] 播报: $text');
      print('[VoiceSynthesisService] 参数: volume=$_volume, pitch=$_pitch, rate=$_rate');
    } catch (e) {
      print('[VoiceSynthesisService] 播报失败: $e');
      _status = VoiceSynthesisStatus.error;
    }
  }

  /// 停止播报
  Future<void> stop() async {
    if (_status != VoiceSynthesisStatus.playing) {
      return;
    }

    try {
      // 停止播报
      await _tts.stop();
      
      _status = VoiceSynthesisStatus.ready;
      _queue.clear();
      _isProcessingQueue = false;
      print('[VoiceSynthesisService] 停止播报');
    } catch (e) {
      print('[VoiceSynthesisService] 停止失败: $e');
    }
  }

  /// 暂停播报
  Future<void> pause() async {
    if (_status != VoiceSynthesisStatus.playing) {
      return;
    }

    try {
      // 暂停播报
      await _tts.pause();
      
      _status = VoiceSynthesisStatus.paused;
      print('[VoiceSynthesisService] 暂停播报');
    } catch (e) {
      print('[VoiceSynthesisService] 暂停失败: $e');
    }
  }

  /// 队列播报
  /// 
  /// 将多个文本加入队列，依次播报
  Future<void> speakQueue(List<String> texts) async {
    if (texts.isEmpty) {
      return;
    }

    _queue.addAll(texts);
    
    if (!_isProcessingQueue) {
      _processNextInQueue();
    }
  }

  /// 处理队列中的下一项
  void _processNextInQueue() {
    if (_queue.isEmpty) {
      _isProcessingQueue = false;
      return;
    }

    _isProcessingQueue = true;
    final text = _queue.removeAt(0);
    speak(text);
  }

  /// 设置语言
  Future<void> setLanguage(String language) async {
    if (_language == language) {
      return;
    }

    _language = language;
    
    // 设置语言
    await _tts.setLanguage(language);
    
    print('[VoiceSynthesisService] 切换语言: $language');
  }

  /// 设置音量
  Future<void> setVolume(double volume) async {
    _volume = volume.clamp(0.0, 1.0);
    await _tts.setVolume(_volume);
  }

  /// 设置音调
  Future<void> setPitch(double pitch) async {
    _pitch = pitch.clamp(0.5, 2.0);
    await _tts.setPitch(_pitch);
  }

  /// 设置语速
  Future<void> setSpeechRate(double rate) async {
    _rate = rate.clamp(0.0, 1.0);
    await _tts.setSpeechRate(_rate);
  }

  /// 获取可用语言列表
  Future<List<String>> getLanguages() async {
    List<dynamic> languages = await _tts.getLanguages;
    return languages.cast<String>();
  }

  /// 获取可用语音列表
  Future<List<Map<String, String>>> getVoices() async {
    List<dynamic> voices = await _tts.getVoices;
    return voices.cast<Map<String, String>>();
  }

  /// 释放资源
  Future<void> dispose() async {
    await stop();
    _queue.clear();
    print('[VoiceSynthesisService] 资源已释放');
  }
}
