// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现WebSocket服务，管理在线对战通信 (已迁移至 Socket.io)

import 'dart:async';
import 'package:socket_io_client/socket_io_client.dart' as IO;
import '../models/websocket_message.dart';
import '../models/message_type.dart';
import '../models/move.dart';

/// WebSocket连接状态
enum ConnectionState {
  /// 已断开
  disconnected,
  
  /// 连接中
  connecting,
  
  /// 已连接
  connected,
  
  /// 重连中
  reconnecting,
}

/// WebSocket服务 (Socket.io版)
class WebSocketService {
  static final WebSocketService _instance = WebSocketService._internal();
  factory WebSocketService() => _instance;
  WebSocketService._internal();

  IO.Socket? _socket;
  ConnectionState _state = ConnectionState.disconnected;
  
  final StreamController<WebSocketMessage> _messageController =
      StreamController<WebSocketMessage>.broadcast();
  
  final StreamController<ConnectionState> _stateController =
      StreamController<ConnectionState>.broadcast();

  // Socket.io has built-in reconnection, but we keep this for UI state syncing
  Timer? _reconnectTimer; 
  String? _serverUrl;

  /// 获取消息流
  Stream<WebSocketMessage> get messageStream => _messageController.stream;
  
  /// 获取连接状态流
  Stream<ConnectionState> get stateStream => _stateController.stream;
  
  /// 获取当前连接状态
  ConnectionState get state => _state;
  
  /// 是否已连接
  bool get isConnected => _state == ConnectionState.connected;

  /// 连接到服务器
  Future<bool> connect(String serverUrl) async {
    if (_socket != null && _socket!.connected) {
      print('Socket已连接');
      return true;
    }

    _serverUrl = serverUrl;
    _updateState(ConnectionState.connecting);

    try {
      // Initialize Socket.io
      _socket = IO.io(serverUrl, IO.OptionBuilder()
          .setTransports(['websocket'])
          .disableAutoConnect()
          .build(),);

      _setupListeners();
      _socket!.connect();

      print('正在连接Socket.io服务器: $serverUrl');
      return true;
    } catch (e) {
      print('Socket连接初始化失败: $e');
      _updateState(ConnectionState.disconnected);
      return false;
    }
  }

  void _setupListeners() {
    if (_socket == null) return;

    // --- System Events ---
    _socket!.onConnect((_) {
      print('Socket已连接: ${_socket!.id}');
      _updateState(ConnectionState.connected);
    });

    _socket!.onDisconnect((_) {
      print('Socket已断开');
      _onDisconnected();
    });

    _socket!.onConnectError((data) {
      print('Socket连接错误: $data');
      _updateState(ConnectionState.disconnected);
    });

    // --- Game Events Mapping ---

    // 匹配成功
    // Server: { matchId, opponentId, color, ownId }
    _socket!.on('match_found', (data) {
      try {
        final map = data as Map<String, dynamic>;
        final isFirstPlayer = map['color'] == 'black'; // P1 is black
        
        final msg = WebSocketMessage(
          type: MessageType.matchFound,
          matchId: map['matchId'],
          payload: {
            'opponentId': map['opponentId'],
            'isFirstPlayer': isFirstPlayer,
          },
          timestamp: DateTime.now(),
        );
        _messageController.add(msg);
      } catch (e) {
        print('Error parsing match_found: $e');
      }
    });

    // 收到对手移动
    // Server: MoveData { matchId, from, to, player... }
    _socket!.on('opponent_move', (data) {
      try {
        final map = data as Map<String, dynamic>;
        // Client expects payload['move'] to contain the move data
        final msg = WebSocketMessage(
          type: MessageType.move,
          matchId: map['matchId'],
          payload: {
            'move': map,
          },
          timestamp: DateTime.now(),
        );
        _messageController.add(msg);
      } catch (e) {
        print('Error parsing opponent_move: $e');
      }
    });

    // 移动被拒绝
    _socket!.on('move_rejected', (data) {
      print('Move rejected: $data');
      // Could emit an error message or toast
    });

    // 对手断线
    _socket!.on('opponent_disconnected', (data) {
      // Server: { matchId, message }
      final map = data as Map<String, dynamic>;
      final msg = WebSocketMessage(
          type: MessageType.disconnect,
          matchId: map['matchId'],
          payload: const {},
          timestamp: DateTime.now(),
      );
      _messageController.add(msg);
    });
    
    // 游戏结束
    _socket!.on('game_over', (data) {
       // Server: { matchId, winnerId, reason }
       try {
         final map = data as Map<String, dynamic>;
         final msg = WebSocketMessage(
            type: MessageType.gameOver,
            matchId: map['matchId'],
            payload: {
              'winnerId': map['winnerId'],
              'reason': map['reason'] ?? 'server_decision',
            },
            timestamp: DateTime.now(),
         );
         _messageController.add(msg);
       } catch (e) {
         print('Error parsing game_over: $e');
       }
    });
    
    // 心跳/系统消息
    _socket!.on('message', (data) {
       print('System Message: $data');
    });
  }

  /// 断开连接
  Future<void> disconnect() async {
    _socket?.disconnect();
    _socket?.dispose();
    _socket = null;
    _updateState(ConnectionState.disconnected);
  }

  /// 请求匹配
  Future<void> requestMatch(String playerId) async {
    _emit('request_match', {'playerId': playerId});
  }

  /// 取消匹配
  Future<void> cancelMatch(String playerId) async {
    _emit('cancel_match', {'playerId': playerId});
  }

  /// 发送移动
  Future<void> sendMove(String matchId, Move move) async {
    final moveData = {
      'matchId': matchId,
      'from': {
        'x': move.from.x,
        'y': move.from.y,
      },
      'to': {
        'x': move.to.x,
        'y': move.to.y,
      },
      'player': move.player.name, // 'white' or 'black'
      'capturedPiece': move.capturedPiece != null
          ? {
              'x': move.capturedPiece!.x,
              'y': move.capturedPiece!.y,
            }
          : null,
    };
    
    _emit('submit_move', moveData);
  }

  /// 发送原始事件
  void _emit(String event, dynamic data) {
    if (!isConnected || _socket == null) {
      print('Socket未连接，无法发送: $event');
      return;
    }
    _socket!.emit(event, data);
  }

  /// 处理连接断开
  void _onDisconnected() {
    _updateState(ConnectionState.disconnected);
  }

  /// 更新连接状态
  void _updateState(ConnectionState newState) {
    if (_state != newState) {
      _state = newState;
      _stateController.add(newState);
      print('连接状态变更: ${newState.toString().split('.').last}');
    }
  }

  /// 释放资源
  Future<void> dispose() async {
    await disconnect();
    await _messageController.close();
    await _stateController.close();
  }
}
