// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
// Task: 创建冥想模式事件定义

library;

import 'package:equatable/equatable.dart';
import '../models/position.dart';
import '../models/move.dart';

/// 冥想模式事件基类
sealed class MeditationModeEvent extends Equatable {
  const MeditationModeEvent();

  @override
  List<Object?> get props => [];
}

/// 开始冥想游戏
class StartMeditationGame extends MeditationModeEvent {
  /// 对手类型：true为AI，false为双人
  final bool isAiOpponent;
  
  /// AI难度（仅在isAiOpponent为true时有效）
  /// 1-简单，2-中等，3-困难
  final int aiDifficulty;

  const StartMeditationGame({
    this.isAiOpponent = true,
    this.aiDifficulty = 2,
  });

  @override
  List<Object?> get props => [isAiOpponent, aiDifficulty];
}

/// 语音输入接收
class VoiceInputReceived extends MeditationModeEvent {
  /// 识别的文本
  final String recognizedText;
  
  /// 置信度（0.0-1.0）
  final double confidence;

  const VoiceInputReceived({
    required this.recognizedText,
    required this.confidence,
  });

  @override
  List<Object?> get props => [recognizedText, confidence];
}

/// 语音命令解析完成
class VoiceCommandParsed extends MeditationModeEvent {
  /// 解析出的位置
  final Position? position;
  
  /// 是否为查询指令
  final bool isQuery;
  
  /// 查询类型（如果是查询指令）
  /// 1-我的棋子在哪，2-对方棋子在哪，3-还剩几个，4-可以走哪，5-重复一遍
  final int? queryType;

  const VoiceCommandParsed({
    this.position,
    this.isQuery = false,
    this.queryType,
  });

  @override
  List<Object?> get props => [position, isQuery, queryType];
}

/// 请求播报棋盘状态
class RequestBoardStateAnnouncement extends MeditationModeEvent {
  /// 播报详细程度
  /// 1-简要，2-完整
  final int detailLevel;

  const RequestBoardStateAnnouncement({
    this.detailLevel = 1,
  });

  @override
  List<Object?> get props => [detailLevel];
}

/// 请求播报可用移动
class RequestAvailableMovesAnnouncement extends MeditationModeEvent {
  const RequestAvailableMovesAnnouncement();
}

/// 冥想模式落子
class MeditationMoveMade extends MeditationModeEvent {
  /// 移动对象
  final Move move;

  const MeditationMoveMade(this.move);

  @override
  List<Object?> get props => [move];
}

/// 暂停冥想游戏
class PauseMeditationGame extends MeditationModeEvent {
  /// 暂停原因
  final String reason;

  const PauseMeditationGame({
    this.reason = '用户暂停',
  });

  @override
  List<Object?> get props => [reason];
}

/// 恢复冥想游戏
class ResumeMeditationGame extends MeditationModeEvent {
  const ResumeMeditationGame();
}

/// 退出冥想游戏
class ExitMeditationGame extends MeditationModeEvent {
  const ExitMeditationGame();
}

/// AI思考完成
class AiThinkingCompleted extends MeditationModeEvent {
  /// AI选择的移动
  final Move aiMove;

  const AiThinkingCompleted(this.aiMove);

  @override
  List<Object?> get props => [aiMove];
}

/// 语音播报完成
class VoiceAnnouncementCompleted extends MeditationModeEvent {
  const VoiceAnnouncementCompleted();
}
