// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 定义游戏规则相关常量

/// 游戏规则常量
class GameConstants {
  GameConstants._();

  /// 棋盘尺寸（4x4）
  static const int boardSize = 4;

  /// 每方棋子数量
  static const int piecesPerPlayer = 4;

  /// 无吃子最大步数（防止无限循环）
  static const int maxMovesWithoutCapture = 50;

  /// 形成三子连线需要的棋子数
  static const int lineLength = 3;

  /// 棋盘总格子数
  static const int totalCells = boardSize * boardSize;

  /// 初始棋子位置（行号）
  static const int blackStartRow = 0;
  static const int whiteStartRow = 3;
}
