// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 定义网络相关常量（超时时间、重试次数等）

/// 网络常量
class NetworkConstants {
  NetworkConstants._();

  // ========== WebSocket配置 ==========
  
  /// 心跳间隔（秒）
  static const Duration heartbeatInterval = Duration(seconds: 30);
  
  /// 重连延迟（秒）
  static const Duration reconnectDelay = Duration(seconds: 3);
  
  /// 最大重连次数
  static const int maxReconnectAttempts = 5;
  
  /// 连接超时时间
  static const Duration connectionTimeout = Duration(seconds: 10);
  
  /// 消息发送超时时间
  static const Duration messageSendTimeout = Duration(seconds: 5);

  // ========== HTTP配置 ==========
  
  /// HTTP请求超时时间
  static const Duration httpTimeout = Duration(seconds: 30);
  
  /// HTTP最大重试次数
  static const int httpMaxRetries = 3;

  // ========== 服务器URL配置 ==========
  
  /// 默认WebSocket服务器URL（开发环境）
  static const String defaultWebSocketUrl = 'ws://localhost:8080/game';
  
  /// 生产环境WebSocket服务器URL
  static const String productionWebSocketUrl = 'wss://game.example.com/ws';
}
