// Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
// Task: 预设主题配置 - 定义经典木纹、现代简约、深夜模式三种主题

import 'package:flutter/material.dart';
import '../models/board_theme.dart';

/// 预设主题配置
class ThemePresets {
  ThemePresets._();

  /// 经典木纹主题
  static const BoardTheme classicWood = BoardTheme(
    id: 'classic_wood',
    name: '经典木纹',
    backgroundColor: Color(0xFFDEB887), // 浅褐色木纹
    gridColor: Color(0xFF8B4513), // 深棕色
    gridLineWidth: 2.0,
    pieceStyle: PieceStyle.classic,
    selectionColor: Colors.amber,
    moveHintColor: Colors.green,
    lastMoveColor: Colors.blue,
    backgroundTexture: 'wood',
  );

  /// 现代简约主题
  static const BoardTheme modernMinimal = BoardTheme(
    id: 'modern_minimal',
    name: '现代简约',
    backgroundColor: Colors.white, // 纯白背景
    gridColor: Color(0xFFE0E0E0), // 浅灰色
    gridLineWidth: 1.0,
    pieceStyle: PieceStyle.flat,
    selectionColor: Colors.blue,
    moveHintColor: Color(0xFF64B5F6), // 浅蓝色
    lastMoveColor: Color(0xFF42A5F5),
    backgroundTexture: 'linen',
  );

  /// 深夜模式主题
  static const BoardTheme darkNight = BoardTheme(
    id: 'dark_night',
    name: '深夜模式',
    backgroundColor: Color(0xFF263238), // 深蓝灰色
    gridColor: Color(0xFF64B5F6), // 淡蓝色
    gridLineWidth: 1.5,
    pieceStyle: PieceStyle.glowing,
    selectionColor: Colors.cyan,
    moveHintColor: Colors.tealAccent,
    lastMoveColor: Color(0xFF26C6DA),
    backgroundTexture: 'night',
  );

  /// 所有预设主题列表
  static const List<BoardTheme> all = [
    classicWood,
    modernMinimal,
    darkNight,
  ];

  /// 根据ID获取主题
  static BoardTheme? getById(String id) {
    try {
      return all.firstWhere((theme) => theme.id == id);
    } catch (e) {
      return null;
    }
  }

  /// 默认主题
  static const BoardTheme defaultTheme = classicWood;
}
