// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 定义UI相关常量（尺寸、间距、动画时长等）

import 'package:flutter/material.dart';

/// UI常量
class UIConstants {
  UIConstants._();

  // ========== 棋盘相关 ==========
  
  /// 棋盘最小尺寸（逻辑像素）
  static const double boardMinSize = 200.0;
  
  /// 棋盘最大尺寸（逻辑像素）
  static const double boardMaxSize = 600.0;
  
  /// 棋盘占屏幕比例
  static const double boardScreenRatio = 0.8;
  
  /// 棋子半径比例（相对于格子大小）
  static const double pieceRadiusRatio = 0.35;
  
  /// 选中高亮圆环半径比例
  static const double selectionRadiusRatio = 0.45;
  
  /// 移动提示圆点半径比例
  static const double moveHintRadiusRatio = 0.15;
  
  /// 棋子高光半径比例（白棋）
  static const double pieceHighlightRatio = 0.2;
  static const double pieceHighlightOffset = 0.3;

  // ========== 颜色 ==========
  
  /// 棋盘背景色（木色）
  static const Color boardBackgroundColor = Color(0xFFDEB887);
  
  /// 棋盘网格线颜色（深棕色）
  static const Color boardGridColor = Color(0xFF8B4513);
  
  /// 选中高亮颜色
  static const Color selectionColor = Colors.amber;
  
  /// 合法移动提示颜色
  static const Color moveHintColor = Colors.green;
  
  /// 最后移动标记颜色
  static const Color lastMoveColor = Colors.blue;

  // ========== 线条宽度 ==========
  
  /// 网格线宽度
  static const double gridLineWidth = 2.0;
  
  /// 棋子边框宽度
  static const double pieceBorderWidth = 2.0;
  
  /// 选中圆环宽度
  static const double selectionRingWidth = 3.0;
  
  /// 移动提示边框宽度
  static const double moveHintBorderWidth = 2.0;
  
  /// 最后移动箭头宽度
  static const double lastMoveArrowWidth = 3.0;
  
  /// 箭头头部大小
  static const double arrowHeadSize = 10.0;

  // ========== 透明度 ==========
  
  /// 阴影透明度
  static const double shadowOpacity = 0.3;
  
  /// 选中光晕透明度
  static const double selectionGlowOpacity = 0.3;
  
  /// 合法移动提示透明度
  static const double moveHintOpacity = 0.5;
  
  /// 最后移动标记背景透明度
  static const double lastMoveBackgroundOpacity = 0.2;
  
  /// 最后移动箭头透明度
  static const double lastMoveArrowOpacity = 0.6;

  // ========== 动画时长 ==========
  
  /// 默认动画时长
  static const Duration defaultAnimationDuration = Duration(milliseconds: 300);
  
  /// 棋子移动动画时长
  static const Duration pieceMoveAnimationDuration = Duration(milliseconds: 300);
  
  /// 吃子动画时长
  static const Duration captureAnimationDuration = Duration(milliseconds: 400);
  
  /// 选中效果动画时长
  static const Duration selectionAnimationDuration = Duration(milliseconds: 200);
  
  /// 页面切换动画时长
  static const Duration pageTransitionDuration = Duration(milliseconds: 300);

  // ========== 间距和内边距 ==========
  
  /// 小间距
  static const double spacingSmall = 8.0;
  
  /// 中等间距
  static const double spacingMedium = 16.0;
  
  /// 大间距
  static const double spacingLarge = 24.0;
  
  /// 超大间距
  static const double spacingExtraLarge = 32.0;
  
  /// 小内边距
  static const EdgeInsets paddingSmall = EdgeInsets.all(8.0);
  
  /// 中等内边距
  static const EdgeInsets paddingMedium = EdgeInsets.all(16.0);
  
  /// 大内边距
  static const EdgeInsets paddingLarge = EdgeInsets.all(24.0);

  // ========== 圆角半径 ==========
  
  /// 小圆角
  static const double borderRadiusSmall = 8.0;
  
  /// 中等圆角
  static const double borderRadiusMedium = 12.0;
  
  /// 大圆角
  static const double borderRadiusLarge = 16.0;

  // ========== 阴影 ==========
  
  /// 棋盘阴影
  static BoxShadow get boardShadow => BoxShadow(
        color: Colors.black.withValues(alpha: shadowOpacity),
        blurRadius: 10,
        offset: const Offset(0, 5),
      );

  /// 棋子阴影偏移
  static const Offset pieceShadowOffset = Offset(2, 2);
  
  /// 棋子阴影模糊半径
  static const double pieceShadowBlur = 3.0;

  // ========== 模糊效果 ==========
  
  /// 选中光晕模糊半径
  static const double selectionGlowBlur = 8.0;

  // ========== 按钮防抖 ==========
  
  /// 按钮防抖时长（防止快速重复点击）
  static const Duration buttonDebounceDelay = Duration(milliseconds: 500);
}
