// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现吃子检测器，检测移动后是否形成吃子情况

import '../models/board_state.dart';
import '../models/position.dart';
import '../models/piece_type.dart';

/// 吃子检测器
///
/// 负责检测移动后是否可以吃子
///
/// 吃子规则：
/// 移动后，如果在某个方向（上/下/左/右）形成"己-己-敌"的连续三子，则吃掉敌方棋子
/// 移动的棋子必须参与这个三子连线
class CaptureDetector {
  /// 四个方向的偏移量：上、下、左、右
  static const List<Position> _directions = [
    Position(0, -1), // 上
    Position(0, 1), // 下
    Position(-1, 0), // 左
    Position(1, 0), // 右
  ];

  /// Detects captures created by the piece that has just moved.
  ///
  /// The formal rules evaluate the complete four-cell row and column through
  /// [movedPiece]. A list is returned because one move may capture once on
  /// each axis.
  List<Position> detectCaptures(
    BoardState board, {
    required Position movedPiece,
    required PieceType player,
  }) {
    if (!movedPiece.isValid() || player == PieceType.empty) {
      return const [];
    }

    final row = List<Position>.generate(
      4,
      (x) => Position(x, movedPiece.y),
    );
    final captured = <Position>[];
    final rowCapture = _detectLineCapture(
      board,
      line: row,
      movedPiece: movedPiece,
      player: player,
    );
    if (rowCapture != null) {
      captured.add(rowCapture);
    }

    final column = List<Position>.generate(
      4,
      (y) => Position(movedPiece.x, y),
    );
    final columnCapture = _detectLineCapture(
      board,
      line: column,
      movedPiece: movedPiece,
      player: player,
    );
    if (columnCapture != null) {
      captured.add(columnCapture);
    }

    return captured;
  }

  Position? _detectLineCapture(
    BoardState board, {
    required List<Position> line,
    required Position movedPiece,
    required PieceType player,
  }) {
    final enemy = player.getOpponent();
    final pieces = line.map(board.getPiece).toList(growable: false);
    final patterns = <({List<PieceType> pieces, int capturedIndex})>[
      (
        pieces: [player, player, enemy, PieceType.empty],
        capturedIndex: 2,
      ),
      (
        pieces: [PieceType.empty, player, player, enemy],
        capturedIndex: 3,
      ),
      (
        pieces: [PieceType.empty, enemy, player, player],
        capturedIndex: 1,
      ),
      (
        pieces: [enemy, player, player, PieceType.empty],
        capturedIndex: 0,
      ),
    ];

    for (final pattern in patterns) {
      if (_samePieces(pieces, pattern.pieces)) {
        final playerPositions = <Position>[
          for (var index = 0; index < line.length; index++)
            if (pattern.pieces[index] == player) line[index],
        ];
        if (playerPositions.contains(movedPiece)) {
          return line[pattern.capturedIndex];
        }
      }
    }

    return null;
  }

  bool _samePieces(List<PieceType> actual, List<PieceType> expected) {
    for (var index = 0; index < actual.length; index++) {
      if (actual[index] != expected[index]) {
        return false;
      }
    }
    return true;
  }

  /// 旧单吃接口，仅供尚未迁移的调用方读取第一个结果。
  @Deprecated('Use detectCaptures to preserve horizontal and vertical captures')
  Position? detectCapture(
    BoardState board,
    Position movedPiece,
    PieceType player,
  ) {
    final captures = detectCaptures(
      board,
      movedPiece: movedPiece,
      player: player,
    );
    return captures.isEmpty ? null : captures.first;
  }

  /// 检测所有可能的吃子机会
  ///
  /// 返回所有可以吃子的移动
  /// Map的key是起始位置，value是一个Map，其中key是目标位置，value是被吃棋子位置
  Map<Position, Map<Position, Position>> getAllCaptureOpportunities(
    BoardState board,
    PieceType player,
  ) {
    final result = <Position, Map<Position, Position>>{};
    final pieces = board.getAllPieces(player);

    for (final piece in pieces) {
      // 获取该棋子的所有相邻空位
      final adjacentPositions = piece.getAdjacentPositions();
      final emptyPositions =
          adjacentPositions.where((pos) => board.isEmpty(pos)).toList();

      for (final target in emptyPositions) {
        // 模拟移动
        final newBoard = board.movePiece(piece, target);

        // 检测是否能吃子
        final captures = detectCaptures(
          newBoard,
          movedPiece: target,
          player: player,
        );

        if (captures.isNotEmpty) {
          result[piece] ??= {};
          result[piece]![target] = captures.first;
        }
      }
    }

    return result;
  }

  /// 检查指定位置的棋子是否有被吃的风险
  ///
  /// 返回可能吃掉该棋子的对手移动
  List<CaptureRisk> getCaptureRisks(
    BoardState board,
    Position piece,
  ) {
    final pieceType = board.getPiece(piece);
    if (pieceType == PieceType.empty) {
      return [];
    }

    final enemy = pieceType.getOpponent();
    final risks = <CaptureRisk>[];

    // 检查四个方向
    for (final direction in _directions) {
      // 检查"敌-己-己"的情况（敌方移动到piece前面）
      final pos0 = Position(piece.x - direction.x, piece.y - direction.y);
      final pos1 = piece;
      final pos2 = Position(piece.x + direction.x, piece.y + direction.y);

      if (pos0.isValid() && pos2.isValid()) {
        if (board.isEmpty(pos0) &&
            board.getPiece(pos1) == pieceType &&
            board.getPiece(pos2) == pieceType) {
          // 如果敌方棋子能移动到pos0，就能吃掉pos2
          risks.add(
            CaptureRisk(
              threatenedPiece: pos2,
              enemyTarget: pos0,
            ),
          );
        }
      }

      // 检查"己-己-敌"的情况（piece可能被吃）
      final back1 = Position(piece.x - direction.x, piece.y - direction.y);
      final back2 =
          Position(piece.x - 2 * direction.x, piece.y - 2 * direction.y);

      if (back1.isValid() && back2.isValid()) {
        if (board.getPiece(back2) == enemy && board.getPiece(back1) == enemy) {
          // 当前piece有被吃的风险
          risks.add(
            CaptureRisk(
              threatenedPiece: piece,
              enemyTarget: null, // 已经形成威胁
            ),
          );
        }
      }
    }

    return risks;
  }
}

/// 吃子风险信息
class CaptureRisk {
  /// 受威胁的棋子位置
  final Position threatenedPiece;

  /// 敌方需要移动到的目标位置（如果为null表示已形成威胁）
  final Position? enemyTarget;

  const CaptureRisk({
    required this.threatenedPiece,
    this.enemyTarget,
  });

  @override
  String toString() {
    return 'CaptureRisk(threatened: $threatenedPiece, enemyTarget: $enemyTarget)';
  }
}
