/// Game Page - 完整游戏页面
///
/// 职责：
/// - 集成GameBloc状态管理
/// - 显示棋盘和游戏信息
/// - 处理用户交互
/// - 响应游戏状态变化
library;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../bloc/game_bloc.dart';
import '../../bloc/game_event.dart';
import '../../bloc/game_state.dart';
import '../../models/position.dart';
import '../../models/piece_type.dart';
import '../widgets/themed_board_widget.dart'; // 暂时使用静态棋盘替代动画棋盘
import '../widgets/game_info_panel.dart';
import '../widgets/game_over_dialog.dart';
import '../widgets/first_player_indicator.dart';
import 'game_replay_page.dart'; // 导入回放页面

/// 游戏页面
class GamePage extends StatelessWidget {
  final GameMode mode;
  final String? aiDifficulty;
  final bool resumeSavedGame;

  const GamePage({
    super.key,
    this.mode = GameMode.pvp,
    this.aiDifficulty,
    this.resumeSavedGame = false,
  });

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) {
        final bloc = GameBloc();
        if (resumeSavedGame) {
          bloc.add(const LoadGameEvent());
        } else {
          bloc.add(
            NewGameEvent(
              mode: mode,
              aiDifficulty: aiDifficulty,
            ),
          );
        }
        return bloc;
      },
      child: const _GamePageContent(),
    );
  }
}

class _GamePageContent extends StatefulWidget {
  const _GamePageContent();

  @override
  State<_GamePageContent> createState() => _GamePageContentState();
}

class _GamePageContentState extends State<_GamePageContent>
    with WidgetsBindingObserver {
  // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
  // Task: 添加先手方提示动画显示状态控制

  /// 是否显示先手方提示动画
  bool _showFirstPlayerIndicator = false;

  /// 先手方
  PieceType? _firstPlayer;
  Timer? _displayTicker;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _displayTicker = Timer.periodic(const Duration(seconds: 1), (_) {
      if (mounted) setState(() {});
    });
    // 在下一帧检查是否需要显示先手提示
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _checkFirstPlayerIndicator();
    });
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final bloc = context.read<GameBloc>();
    final now = DateTime.now();
    switch (state) {
      case AppLifecycleState.resumed:
        bloc.add(ResumeTurnClockEvent(now));
        return;
      case AppLifecycleState.inactive:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        bloc.add(PauseTurnClockEvent(now));
        return;
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _displayTicker?.cancel();
    super.dispose();
  }

  /// 检查是否需要显示先手提示
  void _checkFirstPlayerIndicator() {
    final state = context.read<GameBloc>().state;
    if (state is GamePlaying &&
        state.firstPlayer != null &&
        state.mode == GameMode.pvp) {
      setState(() {
        _firstPlayer = state.firstPlayer;
        _showFirstPlayerIndicator = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Scaffold(
      appBar: AppBar(
        title: const Text('四子游戏'),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          BlocConsumer<GameBloc, GameState>(
            listener: (context, state) {
              // 监听游戏结束状态
              if (state is GameOver) {
                _showGameOverDialog(context, state);
              }
            },
            builder: (context, state) {
              if (state is GameInitial || state is GameLoading) {
                return const Center(
                  child: CircularProgressIndicator(),
                );
              }

              if (state is GameError) {
                return LayoutBuilder(
                  builder: (context, constraints) => SingleChildScrollView(
                    padding: const EdgeInsets.all(16),
                    child: ConstrainedBox(
                      constraints: BoxConstraints(
                        minHeight: constraints.maxHeight > 32
                            ? constraints.maxHeight - 32
                            : 0,
                      ),
                      child: Center(
                        child: ConstrainedBox(
                          constraints: const BoxConstraints(maxWidth: 480),
                          child: Card(
                            child: Padding(
                              padding: const EdgeInsets.all(28),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(
                                    Icons.error_outline_rounded,
                                    size: 56,
                                    color: scheme.error,
                                  ),
                                  const SizedBox(height: 16),
                                  Text(
                                    '棋局暂时无法继续',
                                    style: theme.textTheme.titleLarge,
                                  ),
                                  const SizedBox(height: 8),
                                  Text(
                                    state.errorMessage,
                                    textAlign: TextAlign.center,
                                    style: theme.textTheme.bodyMedium?.copyWith(
                                      color: scheme.onSurfaceVariant,
                                    ),
                                  ),
                                  const SizedBox(height: 20),
                                  FilledButton.icon(
                                    onPressed: () {
                                      context
                                          .read<GameBloc>()
                                          .add(const RestartGameEvent());
                                    },
                                    icon: const Icon(Icons.refresh_rounded),
                                    label: const Text('重新开始'),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                );
              }

              // GamePlaying 或 GameOver 状态
              return _buildGameContent(context, state);
            },
          ),
          // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
          // Task: 显示先手方提示动画覆盖层
          if (_showFirstPlayerIndicator && _firstPlayer != null)
            Container(
              color: Colors.black.withValues(alpha: 0.5),
              child: Center(
                child: FirstPlayerIndicator(
                  firstPlayer: _firstPlayer!,
                  onAnimationComplete: () {
                    setState(() {
                      _showFirstPlayerIndicator = false;
                    });
                  },
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildGameContent(BuildContext context, GameState state) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isLandscape = constraints.maxWidth > constraints.maxHeight;

        if (isLandscape) {
          // 横屏布局：棋盘在左，信息面板在右
          return Row(
            children: [
              Expanded(
                flex: 2,
                child: Center(
                  child: _buildBoard(context, state),
                ),
              ),
              Expanded(
                flex: 1,
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: _buildInfoPanel(context, state),
                ),
              ),
            ],
          );
        } else {
          // 竖屏布局：棋盘在上，信息面板在下
          return Column(
            children: [
              Expanded(
                flex: 2,
                child: Center(
                  child: _buildBoard(context, state),
                ),
              ),
              Expanded(
                flex: 1,
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: _buildInfoPanel(context, state),
                ),
              ),
            ],
          );
        }
      },
    );
  }

  Widget _buildBoard(BuildContext context, GameState state) {
    // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
    // Task: 根据先手方和当前玩家决定是否翻转棋盘视角

    // 在双人对战模式下，如果当前玩家是白方，翻转棋盘确保当前玩家在屏幕下方
    // 在人机对战模式下，如果当前玩家是白方（AI），也翻转棋盘确保玩家（黑方）在下方
    bool shouldFlipBoard = false;

    if (state.mode == GameMode.pvp && state is GamePlaying) {
      // 双人对战：白方先手时翻转棋盘（让白方在下方）
      shouldFlipBoard = state.firstPlayer == PieceType.white;
    } else if (state.mode == GameMode.pve) {
      shouldFlipBoard = state.humanPlayer == PieceType.white;
    }

    return ThemedBoardWidget(
      boardState: state.boardState,
      selectedPiece: state.selectedPiece,
      validMoves: state.validMoves,
      lastMoveFrom: state.lastMove?.from,
      lastMoveTo: state.lastMove?.to,
      capturedPiecePosition: state.lastCapturedPosition,
      flipBoard: shouldFlipBoard,
      onPositionTapped: (position) =>
          _handlePositionTapped(context, state, position),
    );
  }

  Widget _buildInfoPanel(BuildContext context, GameState state) {
    final isAIThinking = state is GamePlaying && state.isAIThinking;
    final aiProgress = state is GamePlaying ? state.aiThinkingProgress : 0.0;
    final aiStatus = state is GamePlaying ? state.aiThinkingStatus : '';

    return GameInfoPanel(
      currentPlayer: state.currentPlayer,
      blackPieceCount: state.blackPieceCount,
      whitePieceCount: state.whitePieceCount,
      moveHistory: state.moveHistory,
      canUndo: state.canUndo && !isAIThinking,
      canRedo: state.canRedo && !isAIThinking,
      isAIThinking: isAIThinking,
      aiThinkingProgress: aiProgress,
      aiThinkingStatus: aiStatus,
      turnRemaining:
          state.turnClock?.remainingAt(DateTime.now()) ?? Duration.zero,
      onUndo: () {
        context.read<GameBloc>().add(const UndoMoveEvent());
      },
      onRedo: () {
        context.read<GameBloc>().add(const RedoMoveEvent());
      },
      onRestart: () {
        _showRestartConfirmation(context);
      },
    );
  }

  void _handlePositionTapped(
    BuildContext context,
    GameState state,
    Position position,
  ) {
    if (state is! GamePlaying) return;
    if (state.isAIThinking) return;

    final bloc = context.read<GameBloc>();
    final piece = state.boardState.getPiece(position);

    // 如果有选中的棋子
    if (state.selectedPiece != null) {
      // 点击同一个位置 -> 取消选中
      if (state.selectedPiece == position) {
        bloc.add(const DeselectPieceEvent());
      }
      // 点击合法移动位置 -> 移动
      else if (state.validMoves.contains(position)) {
        bloc.add(
          MovePieceEvent(
            from: state.selectedPiece!,
            to: position,
          ),
        );
      }
      // 点击己方其他棋子 -> 重新选中
      else if (piece == state.currentPlayer) {
        bloc.add(SelectPieceEvent(position));
      }
      // 其他情况 -> 取消选中
      else {
        bloc.add(const DeselectPieceEvent());
      }
    }
    // 没有选中的棋子
    else {
      // 点击己方棋子 -> 选中
      if (piece == state.currentPlayer) {
        bloc.add(SelectPieceEvent(position));
      }
    }
  }

  void _showGameOverDialog(BuildContext context, GameOver state) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      showGameOverDialog(
        context,
        winner: state.winner,
        gameResult: state.gameResult!,
        onRestart: () {
          Navigator.of(context).pop();
          context.read<GameBloc>().add(const RestartGameEvent());
        },
        onExit: () {
          Navigator.of(context).pop();
          Navigator.of(context).pop();
        },
        onReplay: state.moveHistory.isNotEmpty
            ? () {
                Navigator.of(context).pop();
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => GameReplayPage(
                      moveHistory: state.moveHistory,
                      startingPlayer: state.firstPlayer ?? PieceType.black,
                      gameTitle:
                          state.mode == GameMode.pvp ? 'PVP 游戏回放' : 'PVE 游戏回放',
                    ),
                  ),
                );
              }
            : null,
      );
    });
  }

  void _showRestartConfirmation(BuildContext context) {
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('重新开始'),
        content: const Text('确定要重新开始游戏吗？当前进度将丢失。'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(),
            child: const Text('取消'),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              context.read<GameBloc>().add(const RestartGameEvent());
            },
            child: const Text('确定'),
          ),
        ],
      ),
    );
  }
}
