// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-11-24
// Task: 创建冥想模式游戏页面

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../models/piece_type.dart';
import '../../bloc/meditation_mode_bloc.dart';
import '../../bloc/meditation_mode_event.dart';
import '../../bloc/meditation_mode_state.dart';

/// 冥想模式游戏页面
/// 
/// 特点：
/// - 极简黑屏界面
/// - 仅显示必要的文字提示
/// - 大字体显示识别结果
/// - 长按屏幕3秒紧急退出
class MeditationGamePage extends StatefulWidget {
  const MeditationGamePage({super.key});

  @override
  State<MeditationGamePage> createState() => _MeditationGamePageState();
}

class _MeditationGamePageState extends State<MeditationGamePage> {
  // 长按计时器用于紧急退出
  int _longPressSeconds = 0;
  bool _isLongPressing = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: SafeArea(
        child: GestureDetector(
          // 长按3秒退出
          onLongPressStart: (_) {
            setState(() {
              _isLongPressing = true;
              _longPressSeconds = 0;
            });
            _startLongPressTimer();
          },
          onLongPressEnd: (_) {
            setState(() {
              _isLongPressing = false;
              _longPressSeconds = 0;
            });
          },
          child: Stack(
            children: [
              // 主内容区域
              Center(
                child: BlocBuilder<MeditationModeBloc, MeditationModeState>(
                  builder: (context, state) {
                    return _buildContent(state);
                  },
                ),
              ),

              // 长按退出指示器
              if (_isLongPressing)
                Positioned(
                  bottom: 50,
                  left: 0,
                  right: 0,
                  child: _buildExitIndicator(),
                ),

              // 底部提示
              Positioned(
                bottom: 20,
                left: 0,
                right: 0,
                child: _buildBottomHint(),
              ),
            ],
          ),
        ),
      ),
    );
  }

  /// 构建主内容
  Widget _buildContent(MeditationModeState state) {
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // 冥想图标
          const Icon(
            Icons.self_improvement,
            size: 80,
            color: Colors.white30,
          ),

          const SizedBox(height: 32),

          // 模式标题
          const Text(
            '冥想模式',
            style: TextStyle(
              fontSize: 32,
              fontWeight: FontWeight.bold,
              color: Colors.white70,
            ),
          ),

          const SizedBox(height: 48),

          // 状态显示
          _buildStateDisplay(state),
        ],
      ),
    );
  }

  /// 构建状态显示
  Widget _buildStateDisplay(MeditationModeState state) {
    if (state is VoiceGuiding) {
      return _buildGuidingDisplay();
    } else if (state is WaitingVoiceInput) {
      return _buildWaitingDisplay(state);
    } else if (state is ProcessingVoiceCommand) {
      return _buildProcessingDisplay(state);
    } else if (state is AiThinking) {
      return _buildAiThinkingDisplay();
    } else if (state is MeditationGameOver) {
      return _buildGameOverDisplay(state);
    } else {
      return const SizedBox.shrink();
    }
  }

  /// 引导中显示
  Widget _buildGuidingDisplay() {
    return Column(
      children: [
        _buildStatusIcon(Icons.volume_up, Colors.blue),
        const SizedBox(height: 20),
        const Text(
          '正在播报引导...',
          style: TextStyle(
            fontSize: 20,
            color: Colors.white70,
          ),
        ),
      ],
    );
  }

  /// 等待输入显示
  Widget _buildWaitingDisplay(WaitingVoiceInput state) {
    return Column(
      children: [
        _buildStatusIcon(Icons.mic, Colors.green),
        const SizedBox(height: 20),
        const Text(
          '正在监听您的指令...',
          style: TextStyle(
            fontSize: 20,
            color: Colors.green,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          '当前${state.currentPlayer == PieceType.black ? "黑方" : "白方"}行棋',
          style: const TextStyle(
            fontSize: 16,
            color: Colors.white54,
          ),
        ),
      ],
    );
  }

  /// 处理命令显示
  Widget _buildProcessingDisplay(ProcessingVoiceCommand state) {
    return Column(
      children: [
        _buildStatusIcon(Icons.psychology, Colors.orange),
        const SizedBox(height: 20),
        const Text(
          '正在处理...',
          style: TextStyle(
            fontSize: 18,
            color: Colors.orange,
          ),
        ),
        const SizedBox(height: 24),
        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: Colors.white10,
            borderRadius: BorderRadius.circular(12),
          ),
          child: Column(
            children: [
              const Text(
                '识别结果:',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.white54,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                state.recognizedText,
                style: const TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.bold,
                  color: Colors.greenAccent,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              Text(
                '置信度: ${(state.confidence * 100).toStringAsFixed(0)}%',
                style: const TextStyle(
                  fontSize: 14,
                  color: Colors.white54,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  /// AI思考中显示
  Widget _buildAiThinkingDisplay() {
    return Column(
      children: [
        _buildStatusIcon(Icons.smart_toy, Colors.purple),
        const SizedBox(height: 20),
        const Text(
          'AI正在思考...',
          style: TextStyle(
            fontSize: 20,
            color: Colors.purple,
          ),
        ),
        const SizedBox(height: 20),
        const CircularProgressIndicator(
          color: Colors.purple,
        ),
      ],
    );
  }

  /// 游戏结束显示
  Widget _buildGameOverDisplay(MeditationGameOver state) {
    final isWin = state.winner == PieceType.black;
    
    return Column(
      children: [
        _buildStatusIcon(
          isWin ? Icons.celebration : Icons.sentiment_dissatisfied,
          isWin ? Colors.green : Colors.red,
        ),
        const SizedBox(height: 20),
        Text(
          isWin ? '恭喜获胜！' : '游戏结束',
          style: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: isWin ? Colors.green : Colors.red,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          state.reason,
          style: const TextStyle(
            fontSize: 18,
            color: Colors.white70,
          ),
        ),
        const SizedBox(height: 24),
        ElevatedButton(
          onPressed: () {
            context.read<MeditationModeBloc>().add(const StartMeditationGame());
          },
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.white24,
            padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
          ),
          child: const Text(
            '再来一局',
            style: TextStyle(fontSize: 18, color: Colors.white),
          ),
        ),
      ],
    );
  }

  /// 构建状态图标
  Widget _buildStatusIcon(IconData icon, Color color) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: color.withOpacity(0.2),
        shape: BoxShape.circle,
      ),
      child: Icon(
        icon,
        size: 60,
        color: color,
      ),
    );
  }

  /// 构建退出指示器
  Widget _buildExitIndicator() {
    final progress = _longPressSeconds / 3;
    
    return Center(
      child: Column(
        children: [
          SizedBox(
            width: 100,
            height: 100,
            child: Stack(
              alignment: Alignment.center,
              children: [
                SizedBox(
                  width: 100,
                  height: 100,
                  child: CircularProgressIndicator(
                    value: progress,
                    strokeWidth: 6,
                    backgroundColor: Colors.white24,
                    valueColor: const AlwaysStoppedAnimation<Color>(Colors.red),
                  ),
                ),
                Text(
                  '${3 - _longPressSeconds}',
                  style: const TextStyle(
                    fontSize: 40,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 12),
          const Text(
            '松开取消退出',
            style: TextStyle(
              fontSize: 16,
              color: Colors.white70,
            ),
          ),
        ],
      ),
    );
  }

  /// 构建底部提示
  Widget _buildBottomHint() {
    return Center(
      child: Text(
        '长按屏幕3秒退出冥想模式',
        style: TextStyle(
          fontSize: 14,
          color: Colors.white.withOpacity(0.3),
        ),
      ),
    );
  }

  /// 开始长按计时器
  void _startLongPressTimer() {
    Future.doWhile(() async {
      if (!_isLongPressing) return false;

      await Future.delayed(const Duration(seconds: 1));
      
      if (!mounted || !_isLongPressing) return false;

      setState(() {
        _longPressSeconds++;
      });

      if (_longPressSeconds >= 3) {
        _exitMeditation();
        return false;
      }

      return true;
    });
  }

  /// 退出冥想模式
  void _exitMeditation() {
    context.read<MeditationModeBloc>().add(const ExitMeditationGame());
    Navigator.of(context).pop();
  }

  @override
  void dispose() {
    _isLongPressing = false;
    super.dispose();
  }
}
