// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现游戏设置页面，包含音效、震动、AI难度、主题等配置选项

/// Settings Page - 游戏设置页面
/// 
/// 职责：
/// - 提供游戏设置入口
/// - 支持音效、震动、主题等配置
/// - 自动保存设置
library;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../services/storage_service.dart';
import '../../services/audio_service.dart';
import '../../services/music_service.dart';
import '../../services/audio_coordinator.dart';
import '../../services/performance_monitor.dart';
import '../../services/resource_warmup_service.dart';
import '../../theme/theme_manager.dart';
import '../../models/audio_settings.dart';
import '../../models/display_settings.dart';
import '../../constants/theme_presets.dart';
import '../../constants/storage_constants.dart';
import 'onboarding_page.dart';

/// 设置页面
class SettingsPage extends StatefulWidget {
  const SettingsPage({super.key});

  @override
  State<SettingsPage> createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  final StorageService _storageService = StorageService();
  final AudioCoordinator _audioCoordinator = AudioCoordinator();
  final ThemeManager _themeManager = ThemeManager();
  final PerformanceMonitor _performanceMonitor = PerformanceMonitor();
  final ResourceWarmupService _resourceWarmupService = ResourceWarmupService();
  
  GameSettings _settings = const GameSettings();
  AudioSettings _audioSettings = AudioSettings.defaultSettings;
  DisplaySettings _displaySettings = DisplaySettings.defaultSettings;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    setState(() => _isLoading = true);
    final settings = await _storageService.loadSettings();
    _audioSettings = _audioCoordinator.settings;
    _displaySettings = DisplaySettings(
      themeId: _themeManager.currentBoardTheme.id,
      animationEnabled: settings.animationEnabled,
      particleEnabled: settings.particleEnabled,
      vibrationEnabled: settings.vibrationEnabled,
    );
    setState(() {
      _settings = settings;
      _isLoading = false;
    });
  }

  Future<void> _saveSettings() async {
    await _storageService.saveSettings(_settings);
  }

  void _updateSetting(GameSettings newSettings) {
    setState(() {
      _settings = newSettings;
    });
    _saveSettings();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade50,
      appBar: AppBar(
        title: const Text('设置'),
        elevation: 0,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  _buildSoundSettingsGroup(),
                  const SizedBox(height: 16),
                  _buildVibrationSettingsGroup(),
                  const SizedBox(height: 16),
                  _buildAIDifficultyGroup(),
                  const SizedBox(height: 16),
                  _buildThemeGroup(),
                  const SizedBox(height: 16),
                  _buildPerformanceGroup(),
                  const SizedBox(height: 16),
                  _buildAboutGroup(),
                  const SizedBox(height: 16),
                  _buildDangerZoneGroup(),
                  const SizedBox(height: 32),
                ],
              ),
            ),
    );
  }

  Widget _buildSoundSettingsGroup() {
    return _SettingsGroup(
      title: '音频设置',
      children: [
        _SettingsSwitch(
          label: '音效开关',
          subtitle: '移动、吃子等游戏音效',
          value: _audioSettings.soundEnabled,
          onChanged: (value) async {
            final newSettings = _audioSettings.copyWith(soundEnabled: value);
            await _audioCoordinator.updateSettings(newSettings);
            setState(() => _audioSettings = newSettings);
          },
        ),
        if (_audioSettings.soundEnabled) ...[
          const Divider(),
          _SettingsSlider(
            label: '音效音量',
            value: _audioSettings.soundVolume,
            onChanged: (value) async {
              final newSettings = _audioSettings.copyWith(soundVolume: value);
              await _audioCoordinator.updateSettings(newSettings);
              setState(() => _audioSettings = newSettings);
            },
          ),
        ],
        const Divider(),
        _SettingsSwitch(
          label: '背景音乐',
          subtitle: '游戏背景音乐',
          value: _audioSettings.musicEnabled,
          onChanged: (value) async {
            final newSettings = _audioSettings.copyWith(musicEnabled: value);
            await _audioCoordinator.updateSettings(newSettings);
            setState(() => _audioSettings = newSettings);
          },
        ),
        if (_audioSettings.musicEnabled) ...[
          const Divider(),
          _SettingsSlider(
            label: '音乐音量',
            value: _audioSettings.musicVolume,
            onChanged: (value) async {
              final newSettings = _audioSettings.copyWith(musicVolume: value);
              await _audioCoordinator.updateSettings(newSettings);
              setState(() => _audioSettings = newSettings);
            },
          ),
        ],
        const Divider(),
        _SettingsSwitch(
          label: '语音播报',
          subtitle: '游戏过程语音提示',
          value: _audioSettings.voiceEnabled,
          onChanged: (value) async {
            final newSettings = _audioSettings.copyWith(voiceEnabled: value);
            await _audioCoordinator.updateSettings(newSettings);
            setState(() => _audioSettings = newSettings);
          },
        ),
      ],
    );
  }

  Widget _buildVibrationSettingsGroup() {
    return _SettingsGroup(
      title: '震动设置',
      children: [
        _SettingsSwitch(
          label: '震动反馈',
          subtitle: '触摸和游戏操作时的震动反馈',
          value: _settings.vibrationEnabled,
          onChanged: (value) {
            if (value) {
              HapticFeedback.mediumImpact();
            }
            _updateSetting(_settings.copyWith(vibrationEnabled: value));
          },
        ),
      ],
    );
  }

  Widget _buildAIDifficultyGroup() {
    return _SettingsGroup(
      title: 'AI设置',
      children: [
        _SettingsSelector(
          label: '默认AI难度',
          subtitle: '新游戏的默认AI难度',
          options: const ['easy', 'medium', 'hard'],
          optionLabels: const {
            'easy': '简单',
            'medium': '中等',
            'hard': '困难',
          },
          value: _settings.difficulty,
          onChanged: (value) {
            _updateSetting(_settings.copyWith(difficulty: value));
          },
        ),
      ],
    );
  }

  Widget _buildThemeGroup() {
    final allThemes = ThemePresets.all;
    return _SettingsGroup(
      title: '棋盘主题',
      children: [
        _SettingsSelector(
          label: '主题风格',
          subtitle: '选择喜欢的棋盘风格',
          options: allThemes.map((t) => t.id).toList(),
          optionLabels: {for (var t in allThemes) t.id: t.name},
          value: _displaySettings.themeId,
          onChanged: (value) async {
            await _themeManager.setBoardThemeById(value);
            setState(() {
              _displaySettings = _displaySettings.copyWith(themeId: value);
            });
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text('已切换到${allThemes.firstWhere((t) => t.id == value).name}主题')),
              );
            }
          },
        ),
        const Divider(),
        _SettingsSwitch(
          label: '动画效果',
          subtitle: '棋子移动和吃子动画',
          value: _displaySettings.animationEnabled,
          onChanged: (value) {
            setState(() {
              _displaySettings = _displaySettings.copyWith(animationEnabled: value);
              _settings = _settings.copyWith(animationEnabled: value);
            });
            _saveSettings();
          },
        ),
        const Divider(),
        _SettingsSwitch(
          label: '????????????',
          subtitle: '?????????????????????',
          value: _displaySettings.particleEnabled,
          onChanged: (value) {
            setState(() {
              _displaySettings = _displaySettings.copyWith(particleEnabled: value);
              _settings = _settings.copyWith(particleEnabled: value);
            });
            _saveSettings();
          },
        ),
      ],
    );
  }

    Widget _buildPerformanceGroup() {
    return _SettingsGroup(
      title: '???????????????',
      children: [
        _SettingsSwitch(
          label: '????????????',
          subtitle: '??????????????????????????????',
          value: _settings.performanceMonitoringEnabled,
          onChanged: (value) {
            _performanceMonitor.setEnabled(value);
            _updateSetting(_settings.copyWith(performanceMonitoringEnabled: value));
          },
        ),
        const Divider(),
        _SettingsSwitch(
          label: '???????????????',
          subtitle: '??????????????????????????????',
          value: _settings.resourceWarmupEnabled,
          onChanged: (value) async {
            _updateSetting(_settings.copyWith(resourceWarmupEnabled: value));
            if (value && mounted) {
              await _resourceWarmupService.warmup(context, force: true);
            }
          },
        ),
      ],
    );
  }

Widget _buildAboutGroup() {
    return _SettingsGroup(
      title: '关于',
      children: [
        const _SettingsItem(
          label: '版本号',
          value: '0.1.0',
          icon: Icons.info_outline,
        ),
        const Divider(),
        const _SettingsItem(
          label: '开发者',
          value: 'Qoder AI',
          icon: Icons.code,
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.school),
          title: const Text('重新查看游戏说明'),
          subtitle: const Text('查看新手引导和游戏规则'),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _showOnboarding,
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.article),
          title: const Text('开源许可'),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: () {
            showLicensePage(
              context: context,
              applicationName: '四子游戏',
              applicationVersion: '0.1.0',
            );
          },
        ),
      ],
    );
  }

  Widget _buildDangerZoneGroup() {
    return _SettingsGroup(
      title: '危险操作',
      titleColor: Colors.red,
      children: [
        ListTile(
          leading: const Icon(Icons.delete_outline, color: Colors.red),
          title: const Text(
            '清空统计数据',
            style: TextStyle(color: Colors.red),
          ),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _confirmResetStatistics,
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.restart_alt, color: Colors.red),
          title: const Text(
            '重置所有设置',
            style: TextStyle(color: Colors.red),
          ),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _confirmResetAll,
        ),
      ],
    );
  }

  Future<void> _confirmResetStatistics() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('清空统计数据'),
        content: const Text('确定要清空所有游戏统计数据吗？此操作无法撤销。'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('取消'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('清空'),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      await _storageService.resetStatistics();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('统计数据已清空')),
        );
      }
    }
  }

  Future<void> _confirmResetAll() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('重置所有设置'),
        content: const Text('确定要重置所有设置和数据吗？此操作无法撤销。'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('取消'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('重置'),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      await _storageService.resetAll();
      _loadSettings();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('已重置所有设置')),
        );
      }
    }
  }

  Future<void> _showOnboarding() async {
    // 重置首次启动标记，然后跳转到引导页
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(StorageConstants.keyFirstLaunch, true);
    
    if (mounted) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => const OnboardingPage(),
        ),
      );
    }
  }
}

/// 设置组组件
class _SettingsGroup extends StatelessWidget {
  final String title;
  final List<Widget> children;
  final Color? titleColor;

  const _SettingsGroup({
    required this.title,
    required this.children,
    this.titleColor,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(left: 16, bottom: 8),
          child: Text(
            title,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.bold,
              color: titleColor ?? Colors.grey.shade700,
            ),
          ),
        ),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withValues(alpha: 0.05),
                blurRadius: 10,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Column(
            children: children,
          ),
        ),
      ],
    );
  }
}

/// 开关设置项组件
class _SettingsSwitch extends StatelessWidget {
  final String label;
  final String? subtitle;
  final bool value;
  final ValueChanged<bool> onChanged;

  const _SettingsSwitch({
    required this.label,
    this.subtitle,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return SwitchListTile(
      title: Text(label),
      subtitle: subtitle != null ? Text(subtitle!) : null,
      value: value,
      onChanged: onChanged,
    );
  }
}

/// 滑块设置项组件
class _SettingsSlider extends StatelessWidget {
  final String label;
  final double value;
  final ValueChanged<double> onChanged;
  final ValueChanged<double>? onChangeEnd;

  const _SettingsSlider({
    required this.label,
    required this.value,
    required this.onChanged,
    this.onChangeEnd,
  });

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(label),
      subtitle: Column(
        children: [
          Slider(
            value: value,
            onChanged: onChanged,
            onChangeEnd: onChangeEnd,
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text('0%', style: TextStyle(fontSize: 12)),
              Text(
                '${(value * 100).toInt()}%',
                style: const TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text('100%', style: TextStyle(fontSize: 12)),
            ],
          ),
        ],
      ),
    );
  }
}

/// 选择器设置项组件
class _SettingsSelector extends StatelessWidget {
  final String label;
  final String? subtitle;
  final List<String> options;
  final Map<String, String> optionLabels;
  final String value;
  final ValueChanged<String> onChanged;

  const _SettingsSelector({
    required this.label,
    this.subtitle,
    required this.options,
    required this.optionLabels,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(label),
      subtitle: subtitle != null ? Text(subtitle!) : null,
      trailing: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            optionLabels[value] ?? value,
            style: TextStyle(
              color: Colors.grey.shade600,
              fontSize: 14,
            ),
          ),
          const SizedBox(width: 8),
          const Icon(Icons.arrow_forward_ios, size: 16),
        ],
      ),
      onTap: () {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text(label),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              children: options.map((option) {
                return RadioListTile<String>(
                  title: Text(optionLabels[option] ?? option),
                  value: option,
                  groupValue: value,
                  onChanged: (newValue) {
                    if (newValue != null) {
                      onChanged(newValue);
                      Navigator.pop(context);
                    }
                  },
                );
              }).toList(),
            ),
          ),
        );
      },
    );
  }
}

/// 普通设置项组件
class _SettingsItem extends StatelessWidget {
  final String label;
  final String value;
  final IconData? icon;

  const _SettingsItem({
    required this.label,
    required this.value,
    this.icon,
  });

  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: icon != null ? Icon(icon) : null,
      title: Text(label),
      trailing: Text(
        value,
        style: TextStyle(
          color: Colors.grey.shade600,
          fontSize: 14,
        ),
      ),
    );
  }
}
