// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现游戏设置页面，包含音效、震动、AI难度、主题等配置选项

/// Settings Page - 游戏设置页面
///
/// 职责：
/// - 提供游戏设置入口
/// - 支持音效、震动、主题等配置
/// - 自动保存设置
library;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../services/storage_service.dart';
import '../../services/audio_coordinator.dart';
import '../../services/performance_monitor.dart';
import '../../services/resource_warmup_service.dart';
import '../../services/diagnostics_service.dart';
import '../../services/app_locale_controller.dart';
import '../../models/audio_settings.dart';
import '../../models/display_settings.dart';
import '../../constants/storage_constants.dart';
import '../../l10n/app_localizations.dart';
import 'onboarding_page.dart';

/// 设置页面
class SettingsPage extends StatefulWidget {
  const SettingsPage({super.key});

  @override
  State<SettingsPage> createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  final StorageService _storageService = StorageService();
  final AudioCoordinator _audioCoordinator = AudioCoordinator();
  final PerformanceMonitor _performanceMonitor = PerformanceMonitor();
  final ResourceWarmupService _resourceWarmupService = ResourceWarmupService();

  GameSettings _settings = const GameSettings();
  AudioSettings _audioSettings = AudioSettings.defaultSettings;
  DisplaySettings _displaySettings = DisplaySettings.defaultSettings;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    setState(() => _isLoading = true);
    final settings = await _storageService.loadSettings();
    _audioSettings = _audioCoordinator.settings;
    _displaySettings = DisplaySettings(
      themeId: 'modern_eastern',
      animationEnabled: settings.animationEnabled,
      particleEnabled: settings.particleEnabled,
      vibrationEnabled: settings.vibrationEnabled,
    );
    if (!mounted) {
      return;
    }
    setState(() {
      _settings = settings;
      _isLoading = false;
    });
  }

  Future<void> _saveSettings() async {
    await _storageService.saveSettings(_settings);
  }

  void _updateSetting(GameSettings newSettings) {
    setState(() {
      _settings = newSettings;
    });
    _saveSettings();
  }

  void _updateLocale(String localeCode) {
    _updateSetting(_settings.copyWith(localeCode: localeCode));
    AppLocaleScope.of(context).select(localeCode);
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.settingsTitle),
        elevation: 0,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Align(
                alignment: Alignment.topCenter,
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 760),
                  child: Column(
                    children: [
                      _buildSoundSettingsGroup(),
                      const SizedBox(height: 16),
                      _buildVibrationSettingsGroup(),
                      const SizedBox(height: 16),
                      _buildLanguageGroup(),
                      const SizedBox(height: 16),
                      _buildAIDifficultyGroup(),
                      const SizedBox(height: 16),
                      _buildThemeGroup(),
                      const SizedBox(height: 16),
                      _buildPerformanceGroup(),
                      const SizedBox(height: 16),
                      _buildAboutGroup(),
                      const SizedBox(height: 16),
                      _buildDangerZoneGroup(),
                      const SizedBox(height: 32),
                    ],
                  ),
                ),
              ),
            ),
    );
  }

  Widget _buildSoundSettingsGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsAudioSection,
      children: [
        _SettingsSwitch(
          label: l10n.settingsSoundToggle,
          subtitle: l10n.settingsSoundDescription,
          value: _audioSettings.soundEnabled,
          onChanged: (value) async {
            final newSettings = _audioSettings.copyWith(soundEnabled: value);
            await _audioCoordinator.updateSettings(newSettings);
            setState(() => _audioSettings = newSettings);
          },
        ),
        if (_audioSettings.soundEnabled) ...[
          const Divider(),
          _SettingsSlider(
            label: l10n.settingsSoundVolume,
            value: _audioSettings.soundVolume,
            onChanged: (value) => setState(
              () =>
                  _audioSettings = _audioSettings.copyWith(soundVolume: value),
            ),
            onChangeEnd: (value) => _audioCoordinator.updateSettings(
              _audioSettings.copyWith(soundVolume: value),
            ),
          ),
        ],
        const Divider(),
        _SettingsSwitch(
          label: l10n.settingsMusicToggle,
          subtitle: l10n.settingsMusicDescription,
          value: _audioSettings.musicEnabled,
          onChanged: (value) async {
            final newSettings = _audioSettings.copyWith(musicEnabled: value);
            await _audioCoordinator.updateSettings(newSettings);
            setState(() => _audioSettings = newSettings);
          },
        ),
        if (_audioSettings.musicEnabled) ...[
          const Divider(),
          _SettingsSlider(
            label: l10n.settingsMusicVolume,
            value: _audioSettings.musicVolume,
            onChanged: (value) => setState(
              () =>
                  _audioSettings = _audioSettings.copyWith(musicVolume: value),
            ),
            onChangeEnd: (value) => _audioCoordinator.updateSettings(
              _audioSettings.copyWith(musicVolume: value),
            ),
          ),
        ],
      ],
    );
  }

  Widget _buildVibrationSettingsGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsHapticsSection,
      children: [
        _SettingsSwitch(
          label: l10n.settingsHapticsToggle,
          subtitle: l10n.settingsHapticsDescription,
          value: _settings.vibrationEnabled,
          onChanged: (value) {
            if (value) {
              HapticFeedback.mediumImpact();
            }
            _updateSetting(_settings.copyWith(vibrationEnabled: value));
          },
        ),
      ],
    );
  }

  Widget _buildLanguageGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsLanguageSection,
      children: [
        _SettingsSelector(
          label: l10n.settingsLanguage,
          subtitle: l10n.settingsLanguageDescription,
          options: const ['zh', 'en', 'ja'],
          optionLabels: {
            'zh': l10n.languageChinese,
            'en': l10n.languageEnglish,
            'ja': l10n.languageJapanese,
          },
          value: _settings.localeCode,
          onChanged: _updateLocale,
        ),
      ],
    );
  }

  Widget _buildAIDifficultyGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsAiSection,
      children: [
        _SettingsSelector(
          label: l10n.settingsDefaultAiDifficulty,
          subtitle: l10n.settingsDefaultAiDifficultyDescription,
          options: const ['easy', 'medium', 'hard'],
          optionLabels: {
            'easy': l10n.difficultyEasy,
            'medium': l10n.difficultyMedium,
            'hard': l10n.difficultyHard,
          },
          value: _settings.difficulty,
          onChanged: (value) {
            _updateSetting(_settings.copyWith(difficulty: value));
          },
        ),
      ],
    );
  }

  Widget _buildThemeGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsBoardThemeSection,
      children: [
        ListTile(
          leading: const Icon(Icons.brush_outlined),
          title: Text(l10n.settingsModernEasternTheme),
          subtitle: Text(l10n.settingsModernEasternThemeDescription),
        ),
        const Divider(),
        _SettingsSwitch(
          label: l10n.settingsAnimationToggle,
          subtitle: l10n.settingsAnimationDescription,
          value: _displaySettings.animationEnabled,
          onChanged: (value) {
            setState(() {
              _displaySettings =
                  _displaySettings.copyWith(animationEnabled: value);
              _settings = _settings.copyWith(animationEnabled: value);
            });
            _saveSettings();
          },
        ),
        const Divider(),
        _SettingsSwitch(
          label: l10n.settingsParticleToggle,
          subtitle: l10n.settingsParticleDescription,
          value: _displaySettings.particleEnabled,
          onChanged: (value) {
            setState(() {
              _displaySettings =
                  _displaySettings.copyWith(particleEnabled: value);
              _settings = _settings.copyWith(particleEnabled: value);
            });
            _saveSettings();
          },
        ),
      ],
    );
  }

  Widget _buildPerformanceGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsPrivacyPerformanceSection,
      children: [
        _SettingsSwitch(
          label: l10n.settingsAnonymousDiagnostics,
          subtitle: l10n.settingsAnonymousDiagnosticsDescription,
          value: _settings.performanceMonitoringEnabled,
          onChanged: (value) async {
            _performanceMonitor.setEnabled(value);
            await DiagnosticsService().setEnabled(value);
            _updateSetting(
              _settings.copyWith(performanceMonitoringEnabled: value),
            );
          },
        ),
        const Divider(),
        _SettingsSwitch(
          label: l10n.settingsResourceWarmup,
          subtitle: l10n.settingsResourceWarmupDescription,
          value: _settings.resourceWarmupEnabled,
          onChanged: (value) async {
            _updateSetting(_settings.copyWith(resourceWarmupEnabled: value));
            if (value && mounted) {
              await _resourceWarmupService.warmup(context, force: true);
            }
          },
        ),
      ],
    );
  }

  Widget _buildAboutGroup() {
    final l10n = AppLocalizations.of(context)!;
    return _SettingsGroup(
      title: l10n.settingsAboutSection,
      children: [
        _SettingsItem(
          label: l10n.settingsVersion,
          value: '0.1.0',
          icon: Icons.info_outline,
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.school),
          title: Text(l10n.settingsReviewGuide),
          subtitle: Text(l10n.settingsReviewGuideDescription),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _showOnboarding,
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.article),
          title: Text(l10n.settingsOpenSourceLicenses),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: () {
            showLicensePage(
              context: context,
              applicationName: l10n.appTitle,
              applicationVersion: '0.1.0',
            );
          },
        ),
      ],
    );
  }

  Widget _buildDangerZoneGroup() {
    final l10n = AppLocalizations.of(context)!;
    final error = Theme.of(context).colorScheme.error;
    return _SettingsGroup(
      title: l10n.settingsDangerSection,
      titleColor: error,
      children: [
        ListTile(
          leading: Icon(Icons.delete_outline, color: error),
          title: Text(
            l10n.settingsClearStatistics,
            style: TextStyle(color: error),
          ),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _confirmResetStatistics,
        ),
        const Divider(),
        ListTile(
          leading: Icon(Icons.restart_alt, color: error),
          title: Text(
            l10n.settingsResetAll,
            style: TextStyle(color: error),
          ),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: _confirmResetAll,
        ),
      ],
    );
  }

  Future<void> _confirmResetStatistics() async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(l10n.settingsClearStatistics),
        content: Text(l10n.settingsClearStatisticsConfirm),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text(l10n.cancel),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(
              foregroundColor: Theme.of(context).colorScheme.error,
            ),
            child: Text(l10n.clear),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      await _storageService.resetStatistics();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.settingsStatisticsCleared)),
        );
      }
    }
  }

  Future<void> _confirmResetAll() async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(l10n.settingsResetAll),
        content: Text(l10n.settingsResetAllConfirm),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text(l10n.cancel),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(
              foregroundColor: Theme.of(context).colorScheme.error,
            ),
            child: Text(l10n.settingsResetAll),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      await _storageService.resetAll();
      if (!mounted) {
        return;
      }
      AppLocaleScope.of(context).select('zh');
      await _loadSettings();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.settingsResetAllDone)),
        );
      }
    }
  }

  Future<void> _showOnboarding() async {
    // 重置首次启动标记，然后跳转到引导页
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(StorageConstants.keyFirstLaunch, true);

    if (mounted) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => const OnboardingPage(),
        ),
      );
    }
  }
}

/// 设置组组件
class _SettingsGroup extends StatelessWidget {
  final String title;
  final List<Widget> children;
  final Color? titleColor;

  const _SettingsGroup({
    required this.title,
    required this.children,
    this.titleColor,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(left: 16, bottom: 8),
          child: Text(
            title,
            style: theme.textTheme.labelLarge?.copyWith(
              fontWeight: FontWeight.w700,
              color: titleColor ?? scheme.onSurfaceVariant,
            ),
          ),
        ),
        Card(
          child: Column(
            children: children,
          ),
        ),
      ],
    );
  }
}

/// 开关设置项组件
class _SettingsSwitch extends StatelessWidget {
  final String label;
  final String? subtitle;
  final bool value;
  final ValueChanged<bool> onChanged;

  const _SettingsSwitch({
    required this.label,
    this.subtitle,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return SwitchListTile(
      title: Text(label),
      subtitle: subtitle != null ? Text(subtitle!) : null,
      value: value,
      onChanged: onChanged,
    );
  }
}

/// 滑块设置项组件
class _SettingsSlider extends StatelessWidget {
  final String label;
  final double value;
  final ValueChanged<double> onChanged;
  final ValueChanged<double>? onChangeEnd;

  const _SettingsSlider({
    required this.label,
    required this.value,
    required this.onChanged,
    this.onChangeEnd,
  });

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(label),
      subtitle: Column(
        children: [
          Slider(
            value: value,
            onChanged: onChanged,
            onChangeEnd: onChangeEnd,
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text('0%', style: TextStyle(fontSize: 12)),
              Text(
                '${(value * 100).toInt()}%',
                style: const TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text('100%', style: TextStyle(fontSize: 12)),
            ],
          ),
        ],
      ),
    );
  }
}

/// 选择器设置项组件
class _SettingsSelector extends StatelessWidget {
  final String label;
  final String? subtitle;
  final List<String> options;
  final Map<String, String> optionLabels;
  final String value;
  final ValueChanged<String> onChanged;

  const _SettingsSelector({
    required this.label,
    this.subtitle,
    required this.options,
    required this.optionLabels,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return ListTile(
      title: Text(label),
      subtitle: subtitle != null ? Text(subtitle!) : null,
      trailing: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            optionLabels[value] ?? value,
            style: TextStyle(
              color: scheme.onSurfaceVariant,
              fontSize: 14,
            ),
          ),
          const SizedBox(width: 8),
          const Icon(Icons.arrow_forward_ios, size: 16),
        ],
      ),
      onTap: () {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text(label),
            content: RadioGroup<String>(
              groupValue: value,
              onChanged: (newValue) {
                if (newValue != null) {
                  onChanged(newValue);
                  Navigator.pop(context);
                }
              },
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: options.map((option) {
                  return RadioListTile<String>(
                    title: Text(optionLabels[option] ?? option),
                    value: option,
                  );
                }).toList(),
              ),
            ),
          ),
        );
      },
    );
  }
}

/// 普通设置项组件
class _SettingsItem extends StatelessWidget {
  final String label;
  final String value;
  final IconData? icon;

  const _SettingsItem({
    required this.label,
    required this.value,
    this.icon,
  });

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return ListTile(
      leading: icon != null ? Icon(icon) : null,
      title: Text(label),
      trailing: Text(
        value,
        style: TextStyle(
          color: scheme.onSurfaceVariant,
          fontSize: 14,
        ),
      ),
    );
  }
}
