// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
// Task: 创建冥想模式动画主题抽象基类

library;

import 'package:flutter/material.dart';
import '../../models/board_state.dart';
import '../../models/position.dart';

/// 冥想模式动画主题抽象基类
/// 
/// 定义冥想模式视觉动画的接口规范
/// 所有主题必须实现该接口
abstract class MeditationAnimationTheme {
  /// 主题名称
  String get name;
  
  /// 主题描述
  String get description;
  
  /// 主题标识符
  String get identifier;
  
  /// 主色调
  Color get primaryColor;
  
  /// 背景色
  Color get backgroundColor;

  /// 绘制静态背景
  /// 
  /// [canvas] 画布
  /// [size] 绘制区域大小
  /// [animation] 动画进度（0.0-1.0，用于持续动画）
  void paintBackground(Canvas canvas, Size size, double animation);

  /// 播放落子动画
  /// 
  /// [canvas] 画布
  /// [size] 绘制区域大小
  /// [position] 落子位置
  /// [isPlayer] 是否为玩家落子
  /// [progress] 动画进度（0.0-1.0）
  void animateMove(
    Canvas canvas,
    Size size,
    Position position,
    bool isPlayer,
    double progress,
  );

  /// 播放吃子动画
  /// 
  /// [canvas] 画布
  /// [size] 绘制区域大小
  /// [position] 被吃棋子位置
  /// [progress] 动画进度（0.0-1.0）
  void animateCapture(
    Canvas canvas,
    Size size,
    Position position,
    double progress,
  );

  /// 播放胜利动画
  /// 
  /// [canvas] 画布
  /// [size] 绘制区域大小
  /// [progress] 动画进度（0.0-1.0）
  void animateVictory(Canvas canvas, Size size, double progress);

  /// 绘制当前游戏状态
  /// 
  /// [canvas] 画布
  /// [size] 绘制区域大小
  /// [board] 棋盘状态
  void paintGameState(Canvas canvas, Size size, BoardState board);

  /// 获取主题配置参数
  Map<String, dynamic> getThemeConfig();
}

/// 主题配置数据
class ThemeConfig {
  /// 粒子/图形数量
  final int elementCount;
  
  /// 动画速度倍率
  final double animationSpeed;
  
  /// 视觉强度（0.0-1.0）
  final double intensity;
  
  /// 是否启用拖尾效果
  final bool trailEnabled;
  
  /// 是否启用模糊效果
  final bool blurEnabled;

  const ThemeConfig({
    this.elementCount = 20,
    this.animationSpeed = 1.0,
    this.intensity = 0.8,
    this.trailEnabled = true,
    this.blurEnabled = false,
  });

  Map<String, dynamic> toJson() {
    return {
      'elementCount': elementCount,
      'animationSpeed': animationSpeed,
      'intensity': intensity,
      'trailEnabled': trailEnabled,
      'blurEnabled': blurEnabled,
    };
  }

  factory ThemeConfig.fromJson(Map<String, dynamic> json) {
    return ThemeConfig(
      elementCount: json['elementCount'] as int? ?? 20,
      animationSpeed: json['animationSpeed'] as double? ?? 1.0,
      intensity: json['intensity'] as double? ?? 0.8,
      trailEnabled: json['trailEnabled'] as bool? ?? true,
      blurEnabled: json['blurEnabled'] as bool? ?? false,
    );
  }
}

/// 主题元素（粒子/图形的基本数据结构）
class ThemeElement {
  /// 位置X (0.0-1.0)
  double x;
  
  /// 位置Y (0.0-1.0)
  double y;
  
  /// 速度X
  double vx;
  
  /// 速度Y
  double vy;
  
  /// 大小
  double size;
  
  /// 透明度 (0.0-1.0)
  double opacity;
  
  /// 颜色
  Color color;
  
  /// 生命周期 (0.0-1.0)
  double life;
  
  /// 旋转角度
  double rotation;

  ThemeElement({
    required this.x,
    required this.y,
    this.vx = 0,
    this.vy = 0,
    this.size = 1.0,
    this.opacity = 1.0,
    required this.color,
    this.life = 1.0,
    this.rotation = 0,
  });

  /// 更新元素状态
  void update(double deltaTime) {
    x += vx * deltaTime;
    y += vy * deltaTime;
    rotation += 0.01;
    life -= deltaTime * 0.1;
    
    // 边界检查
    if (x < 0) x += 1.0;
    if (x > 1) x -= 1.0;
    if (y < 0) y += 1.0;
    if (y > 1) y -= 1.0;
  }

  /// 是否存活
  bool get isAlive => life > 0;
}
