// Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
// Task: 音频设置数据模型 - 管理音效/音乐/语音的配置参数

import 'package:equatable/equatable.dart';

/// 音频设置
/// 
/// 包含音效、音乐、语音的开关和音量配置
class AudioSettings extends Equatable {
  /// 音效总开关
  final bool soundEnabled;
  
  /// 音乐总开关
  final bool musicEnabled;
  
  /// 语音总开关
  final bool voiceEnabled;
  
  /// 音效音量 (0.0-1.0)
  final double soundVolume;
  
  /// 音乐音量 (0.0-1.0)
  final double musicVolume;
  
  /// 语音音量 (0.0-1.0)
  final double voiceVolume;
  
  /// 语速 (0.0-1.0)
  final double voiceSpeechRate;
  
  /// 音调 (0.5-2.0)
  final double voicePitch;

  const AudioSettings({
    this.soundEnabled = true,
    this.musicEnabled = true,
    this.voiceEnabled = true,
    this.soundVolume = 0.7,
    this.musicVolume = 0.4,
    this.voiceVolume = 0.8,
    this.voiceSpeechRate = 0.5,
    this.voicePitch = 1.0,
  });

  /// 默认设置
  static const AudioSettings defaultSettings = AudioSettings();

  /// 从Map创建
  factory AudioSettings.fromMap(Map<String, dynamic> map) {
    return AudioSettings(
      soundEnabled: map['soundEnabled'] as bool? ?? true,
      musicEnabled: map['musicEnabled'] as bool? ?? true,
      voiceEnabled: map['voiceEnabled'] as bool? ?? true,
      soundVolume: (map['soundVolume'] as num?)?.toDouble() ?? 0.7,
      musicVolume: (map['musicVolume'] as num?)?.toDouble() ?? 0.4,
      voiceVolume: (map['voiceVolume'] as num?)?.toDouble() ?? 0.8,
      voiceSpeechRate: (map['voiceSpeechRate'] as num?)?.toDouble() ?? 0.5,
      voicePitch: (map['voicePitch'] as num?)?.toDouble() ?? 1.0,
    );
  }

  /// 转换为Map
  Map<String, dynamic> toMap() {
    return {
      'soundEnabled': soundEnabled,
      'musicEnabled': musicEnabled,
      'voiceEnabled': voiceEnabled,
      'soundVolume': soundVolume,
      'musicVolume': musicVolume,
      'voiceVolume': voiceVolume,
      'voiceSpeechRate': voiceSpeechRate,
      'voicePitch': voicePitch,
    };
  }

  /// 复制并修改
  AudioSettings copyWith({
    bool? soundEnabled,
    bool? musicEnabled,
    bool? voiceEnabled,
    double? soundVolume,
    double? musicVolume,
    double? voiceVolume,
    double? voiceSpeechRate,
    double? voicePitch,
  }) {
    return AudioSettings(
      soundEnabled: soundEnabled ?? this.soundEnabled,
      musicEnabled: musicEnabled ?? this.musicEnabled,
      voiceEnabled: voiceEnabled ?? this.voiceEnabled,
      soundVolume: soundVolume ?? this.soundVolume,
      musicVolume: musicVolume ?? this.musicVolume,
      voiceVolume: voiceVolume ?? this.voiceVolume,
      voiceSpeechRate: voiceSpeechRate ?? this.voiceSpeechRate,
      voicePitch: voicePitch ?? this.voicePitch,
    );
  }

  @override
  List<Object?> get props => [
        soundEnabled,
        musicEnabled,
        voiceEnabled,
        soundVolume,
        musicVolume,
        voiceVolume,
        voiceSpeechRate,
        voicePitch,
      ];
}
