// Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
// Task: 棋盘主题数据模型 - 定义主题配置参数

import 'package:flutter/material.dart';
import 'package:equatable/equatable.dart';

/// 棋子绘制风格
enum PieceStyle {
  /// 经典立体风格
  classic,
  
  /// 扁平化风格
  flat,
  
  /// 发光风格
  glowing,
  
  /// 水墨风格
  ink,
}

/// 棋盘主题
/// 
/// 定义棋盘的视觉风格,包括颜色、样式等
class BoardTheme extends Equatable {
  /// 主题唯一标识
  final String id;
  
  /// 主题名称
  final String name;
  
  /// 棋盘背景色
  final Color backgroundColor;
  
  /// 网格线颜色
  final Color gridColor;
  
  /// 网格线宽度
  final double gridLineWidth;
  
  /// 棋子绘制风格
  final PieceStyle pieceStyle;
  
  /// 选中高亮颜色
  final Color selectionColor;
  
  /// 移动提示颜色
  final Color moveHintColor;
  
  /// 最后移动标记颜色
  final Color lastMoveColor;
  
  /// 背景纹理路径(可选)
  final String? backgroundTexture;

  const BoardTheme({
    required this.id,
    required this.name,
    required this.backgroundColor,
    required this.gridColor,
    required this.gridLineWidth,
    required this.pieceStyle,
    required this.selectionColor,
    required this.moveHintColor,
    required this.lastMoveColor,
    this.backgroundTexture,
  });

  /// 从Map创建
  factory BoardTheme.fromMap(Map<String, dynamic> map) {
    return BoardTheme(
      id: map['id'] as String,
      name: map['name'] as String,
      backgroundColor: Color(map['backgroundColor'] as int),
      gridColor: Color(map['gridColor'] as int),
      gridLineWidth: (map['gridLineWidth'] as num).toDouble(),
      pieceStyle: PieceStyle.values.byName(map['pieceStyle'] as String),
      selectionColor: Color(map['selectionColor'] as int),
      moveHintColor: Color(map['moveHintColor'] as int),
      lastMoveColor: Color(map['lastMoveColor'] as int),
      backgroundTexture: map['backgroundTexture'] as String?,
    );
  }

  /// 转换为Map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'backgroundColor': backgroundColor.value,
      'gridColor': gridColor.value,
      'gridLineWidth': gridLineWidth,
      'pieceStyle': pieceStyle.name,
      'selectionColor': selectionColor.value,
      'moveHintColor': moveHintColor.value,
      'lastMoveColor': lastMoveColor.value,
      'backgroundTexture': backgroundTexture,
    };
  }

  /// 复制并修改
  BoardTheme copyWith({
    String? id,
    String? name,
    Color? backgroundColor,
    Color? gridColor,
    double? gridLineWidth,
    PieceStyle? pieceStyle,
    Color? selectionColor,
    Color? moveHintColor,
    Color? lastMoveColor,
    String? backgroundTexture,
  }) {
    return BoardTheme(
      id: id ?? this.id,
      name: name ?? this.name,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      gridColor: gridColor ?? this.gridColor,
      gridLineWidth: gridLineWidth ?? this.gridLineWidth,
      pieceStyle: pieceStyle ?? this.pieceStyle,
      selectionColor: selectionColor ?? this.selectionColor,
      moveHintColor: moveHintColor ?? this.moveHintColor,
      lastMoveColor: lastMoveColor ?? this.lastMoveColor,
      backgroundTexture: backgroundTexture ?? this.backgroundTexture,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        backgroundColor,
        gridColor,
        gridLineWidth,
        pieceStyle,
        selectionColor,
        moveHintColor,
        lastMoveColor,
        backgroundTexture,
      ];
}
