// Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
// Task: 显示设置数据模型 - 管理主题、动画、粒子效果等视觉配置

import 'package:equatable/equatable.dart';

/// 显示设置
/// 
/// 包含主题、动画、粒子效果等视觉配置
class DisplaySettings extends Equatable {
  /// 棋盘主题ID
  final String themeId;
  
  /// 是否启用动画
  final bool animationEnabled;
  
  /// 是否启用粒子效果
  final bool particleEnabled;
  
  /// 是否启用震动反馈
  final bool vibrationEnabled;

  const DisplaySettings({
    this.themeId = 'classic_wood',
    this.animationEnabled = true,
    this.particleEnabled = true,
    this.vibrationEnabled = true,
  });

  /// 默认设置
  static const DisplaySettings defaultSettings = DisplaySettings();

  /// 从Map创建
  factory DisplaySettings.fromMap(Map<String, dynamic> map) {
    return DisplaySettings(
      themeId: map['themeId'] as String? ?? 'classic_wood',
      animationEnabled: map['animationEnabled'] as bool? ?? true,
      particleEnabled: map['particleEnabled'] as bool? ?? true,
      vibrationEnabled: map['vibrationEnabled'] as bool? ?? true,
    );
  }

  /// 转换为Map
  Map<String, dynamic> toMap() {
    return {
      'themeId': themeId,
      'animationEnabled': animationEnabled,
      'particleEnabled': particleEnabled,
      'vibrationEnabled': vibrationEnabled,
    };
  }

  /// 复制并修改
  DisplaySettings copyWith({
    String? themeId,
    bool? animationEnabled,
    bool? particleEnabled,
    bool? vibrationEnabled,
  }) {
    return DisplaySettings(
      themeId: themeId ?? this.themeId,
      animationEnabled: animationEnabled ?? this.animationEnabled,
      particleEnabled: particleEnabled ?? this.particleEnabled,
      vibrationEnabled: vibrationEnabled ?? this.vibrationEnabled,
    );
  }

  @override
  List<Object?> get props => [
        themeId,
        animationEnabled,
        particleEnabled,
        vibrationEnabled,
      ];
}
