// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 创建在线对战匹配状态枚举

/// 在线匹配状态
enum MatchStatus {
  /// 等待匹配
  waiting,
  
  /// 游戏进行中
  playing,
  
  /// 游戏结束
  finished,
  
  /// 连接断开
  disconnected,
}

extension MatchStatusExtension on MatchStatus {
  /// 转换为JSON字符串
  String toJson() {
    return toString().split('.').last;
  }
  
  /// 从JSON字符串创建
  static MatchStatus fromJson(String json) {
    return MatchStatus.values.firstWhere(
      (e) => e.toString().split('.').last == json,
      orElse: () => MatchStatus.waiting,
    );
  }
  
  /// 获取显示名称
  String get displayName {
    switch (this) {
      case MatchStatus.waiting:
        return '等待匹配';
      case MatchStatus.playing:
        return '游戏中';
      case MatchStatus.finished:
        return '已结束';
      case MatchStatus.disconnected:
        return '已断开';
    }
  }
  
  /// 是否可以进行游戏操作
  bool get canPlay => this == MatchStatus.playing;
  
  /// 是否已结束
  bool get isFinished => this == MatchStatus.finished || this == MatchStatus.disconnected;
}
