// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 定义棋子类型枚举和辅助方法

/// 棋子类型
enum PieceType {
  /// 空位
  empty,
  
  /// 黑方棋子
  black,
  
  /// 白方棋子
  white,
}

extension PieceTypeExtension on PieceType {
  /// 获取对手棋子类型
  PieceType getOpponent() {
    switch (this) {
      case PieceType.black:
        return PieceType.white;
      case PieceType.white:
        return PieceType.black;
      case PieceType.empty:
        return PieceType.empty;
    }
  }

  /// 是否为玩家棋子（非empty）
  bool isPlayer() {
    return this != PieceType.empty;
  }

  /// 获取显示名称
  String getDisplayName() {
    switch (this) {
      case PieceType.black:
        return '黑方';
      case PieceType.white:
        return '白方';
      case PieceType.empty:
        return '空位';
    }
  }

  /// 获取简短标识（用于调试）
  String getSymbol() {
    switch (this) {
      case PieceType.black:
        return '●';
      case PieceType.white:
        return '○';
      case PieceType.empty:
        return '·';
    }
  }
}
