// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 主程序入口，启动游戏应用

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ui/screens/home_page.dart';
import 'ui/screens/onboarding_page.dart';
import 'services/storage_service.dart';
import 'services/audio_coordinator.dart';
import 'services/performance_monitor.dart';
import 'theme/theme_manager.dart';
import 'l10n/app_localizations.dart';
import 'constants/storage_constants.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // 初始化存储服务
  final storageService = StorageService();
  await storageService.initialize();
  await ThemeManager().initialize();
  await AudioCoordinator().initialize();
  final settings = await storageService.loadSettings();
  PerformanceMonitor().setEnabled(settings.performanceMonitoringEnabled);
  
  runApp(const FourSquareGameApp());
}

class FourSquareGameApp extends StatefulWidget {
  const FourSquareGameApp({super.key});

  @override
  State<FourSquareGameApp> createState() => _FourSquareGameAppState();
}

class _FourSquareGameAppState extends State<FourSquareGameApp> {
  final StorageService _storageService = StorageService();
  GameTheme _currentTheme = ThemeManager.defaultTheme;
  bool _isLoading = true;
  bool _isFirstLaunch = true;

  @override
  void initState() {
    super.initState();
    _initialize();
  }

  Future<void> _initialize() async {
    await _loadTheme();
    await _checkFirstLaunch();
  }

  Future<void> _loadTheme() async {
    final settings = await _storageService.loadSettings();
    final themeType = ThemeManager.getThemeTypeByName(settings.selectedTheme);
    setState(() {
      _currentTheme = ThemeManager.getTheme(themeType);
      _isLoading = false;
    });
  }

  Future<void> _checkFirstLaunch() async {
    final prefs = await SharedPreferences.getInstance();
    final isFirstLaunch = prefs.getBool(StorageConstants.keyFirstLaunch) ?? true;
    setState(() {
      _isFirstLaunch = isFirstLaunch;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const MaterialApp(
        home: Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        ),
        debugShowCheckedModeBanner: false,
      );
    }

    return MaterialApp(
      title: '四子游戏',
      theme: _currentTheme.materialTheme,
      home: _isFirstLaunch ? const OnboardingPage() : const HomePage(),
      routes: {
        '/home': (context) => const HomePage(),
        '/onboarding': (context) => const OnboardingPage(),
      },
      debugShowCheckedModeBanner: false,
      // 国际化配置
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('zh', ''), // 中文
        Locale('en', ''), // 英文
        Locale('ja', ''), // 日文
      ],
    );
  }
}
