// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 主程序入口，启动游戏应用

import 'package:flutter/material.dart';
import 'ui/screens/home_page.dart';

void main() {
  runApp(const FourSquareGameApp());
}

class FourSquareGameApp extends StatelessWidget {
  const FourSquareGameApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '四子游戏',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.brown),
        useMaterial3: true,
      ),
      home: const HomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}
