// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
// Task: 实现语音命令解析器

import '../models/position.dart';

/// 语音命令解析器
///
/// 负责将语音识别结果解析为游戏指令（Position）
///
/// 支持的格式：
/// 1. 传统坐标: "横1竖2"、"横三竖四"
/// 2. 国际式: "A1"、"B2"、"C3"
/// 3. 方向式: "左上"、"右下"（不自动解释有歧义的中心格）
/// 4. 自然语言: "移动到横2竖3"
class VoiceCommandParser {
  // 用户语音坐标使用1-4，进入引擎前统一转为0-3。
  static const Map<String, int> _spokenNumbers = {
    '一': 1,
    '1': 1,
    '二': 2,
    '2': 2,
    '三': 3,
    '3': 3,
    '四': 4,
    '4': 4,
  };

  static const List<String> _chineseNumerals = ['一', '二', '三', '四'];

  // 英文字母映射（A-D对应0-3）
  static const Map<String, int> _letterCoords = {
    'A': 0,
    'a': 0,
    'B': 1,
    'b': 1,
    'C': 2,
    'c': 2,
    'D': 3,
    'd': 3,
  };

  // 方向坐标映射
  static const Map<String, Position> _directionCoords = {
    '左上': Position(0, 0),
    '右上': Position(3, 0),
    '左下': Position(0, 3),
    '右下': Position(3, 3),
  };

  /// 解析语音指令为Position
  ///
  /// 返回null表示解析失败
  static Position? parse(String command) {
    if (command.isEmpty) {
      return null;
    }

    // 清理命令（移除空格、标点）
    final cleaned = command
        .replaceAll(' ', '')
        .replaceAll('，', '')
        .replaceAll(',', '')
        .replaceAll('。', '')
        .replaceAll('.', '')
        .toLowerCase();

    final candidates = <Position>{
      if (_parseDirection(cleaned) case final position?) position,
      if (_parseTraditional(cleaned) case final position?) position,
      if (_parseInternational(cleaned) case final position?) position,
    };

    // 同一句话给出互相冲突的位置时要求用户重说，不猜测。
    return candidates.length == 1 ? candidates.single : null;
  }

  /// 解析方向式命令
  static Position? _parseDirection(String command) {
    for (final entry in _directionCoords.entries) {
      if (command.contains(entry.key)) {
        return entry.value;
      }
    }
    return null;
  }

  /// 解析传统坐标（横X竖Y）
  static Position? _parseTraditional(String command) {
    // 匹配"横X竖Y"格式
    final horizontalVertical = RegExp(
      r'横([一二三四1234])竖([一二三四1234])',
    ).firstMatch(command);
    if (horizontalVertical != null) {
      final x = _toEngineCoord(horizontalVertical.group(1));
      final y = _toEngineCoord(horizontalVertical.group(2));
      if (x != null && y != null) return Position(x, y);
    }

    final rowColumn = RegExp(
      r'行([一二三四1234])列([一二三四1234])',
    ).firstMatch(command);
    if (rowColumn != null) {
      final y = _toEngineCoord(rowColumn.group(1));
      final x = _toEngineCoord(rowColumn.group(2));
      if (x != null && y != null) return Position(x, y);
    }

    return null;
  }

  /// 解析国际坐标（A1, B2等）
  static Position? _parseInternational(String command) {
    final pattern = RegExp(r'([ABCDabcd])([1234])');
    final match = pattern.firstMatch(command);

    if (match != null) {
      final x = _letterCoords[match.group(1)];
      final y = int.tryParse(match.group(2)!) != null
          ? int.parse(match.group(2)!) - 1 // 用户输入1-4，转为0-3
          : null;

      if (x != null && y != null) {
        return Position(x, y);
      }
    }

    return null;
  }

  static int? _toEngineCoord(String? value) {
    final userCoord = _spokenNumbers[value];
    return userCoord == null ? null : userCoord - 1;
  }

  /// 模糊匹配
  ///
  /// 当精确解析失败时，返回可能的候选位置列表
  static List<Position> fuzzyMatch(String command) {
    final exact = parse(command);
    if (exact != null) return [exact];

    final cleaned = command.replaceAll(RegExp(r'[\s，,。.]'), '');
    final coordinates = RegExp(r'[一二三四1234]')
        .allMatches(cleaned)
        .map((match) => _toEngineCoord(match.group(0)))
        .whereType<int>()
        .toSet();
    final candidates = <Position>[];
    for (final x in coordinates) {
      for (final y in coordinates) {
        candidates.add(Position(x, y));
      }
    }

    return candidates;
  }

  /// 格式化位置为语音文本（用于播报）
  static String formatPosition(Position position) {
    final xChinese = _chineseNumerals[position.x];
    final yChinese = _chineseNumerals[position.y];

    return '横$xChinese竖$yChinese';
  }

  /// 格式化位置为国际坐标（用于显示）
  static String formatPositionInternational(Position position) {
    final letter = _letterCoords.entries
        .firstWhere((e) => e.value == position.x)
        .key
        .toUpperCase();
    final number = position.y + 1;

    return '$letter$number';
  }
}
