# Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
# Task: 生成临时音频文件占位符供开发测试使用

"""
临时音频文件生成脚本

功能:生成简单的正弦波音效文件,用于开发阶段测试
真实音频文件需后续从Freesound/BFXR等平台获取并替换
"""

import numpy as np
import wave
import struct
import os

def generate_sine_wave(frequency, duration_ms, sample_rate=44100):
    """生成正弦波音频数据"""
    num_samples = int(sample_rate * duration_ms / 1000)
    t = np.linspace(0, duration_ms / 1000, num_samples, False)
    wave_data = np.sin(2 * np.pi * frequency * t)
    # 归一化到16位整数
    wave_data = (wave_data * 32767).astype(np.int16)
    return wave_data

def save_wav_file(filename, audio_data, sample_rate=44100):
    """保存为WAV文件"""
    with wave.open(filename, 'w') as wav_file:
        wav_file.setnchannels(1)  # 单声道
        wav_file.setsampwidth(2)   # 16位
        wav_file.setframerate(sample_rate)
        wav_file.writeframes(audio_data.tobytes())

def generate_sound_effects():
    """生成游戏音效文件"""
    sounds_dir = "assets/sounds"
    
    # 确保目录存在
    os.makedirs(sounds_dir, exist_ok=True)
    
    # 音效定义: (文件名, 频率Hz, 时长ms, 说明)
    sound_definitions = [
        ("select.wav", 880, 150, "选中棋子 - C5音调"),
        ("move.wav", 660, 250, "移动棋子 - E5音调"),
        ("capture.wav", 1046, 300, "吃子 - C6音调"),
        ("win.wav", 523, 500, "胜利 - C5长音"),
        ("lose.wav", 392, 500, "失败 - G4低沉音"),
        ("click.wav", 440, 100, "点击 - A4短音"),
    ]
    
    print("开始生成音效文件...")
    for filename, freq, duration, description in sound_definitions:
        filepath = os.path.join(sounds_dir, filename)
        audio_data = generate_sine_wave(freq, duration)
        save_wav_file(filepath, audio_data)
        print(f"✓ {filename} - {description}")
    
    print(f"\n音效文件已生成至: {sounds_dir}")
    print("注意: 这些是临时测试文件,请后续替换为高质量音效")

def generate_music_placeholder():
    """生成音乐占位符文件"""
    music_dir = "assets/sounds/music"
    os.makedirs(music_dir, exist_ok=True)
    
    # 音乐主题定义: (文件名, 基频, 时长秒, 说明)
    music_definitions = [
        ("main.wav", 440, 3, "主菜单音乐占位符"),
        ("gameplay.wav", 330, 3, "游戏音乐占位符"),
    ]
    
    print("\n开始生成音乐占位符...")
    for filename, freq, duration_sec, description in music_definitions:
        filepath = os.path.join(music_dir, filename)
        # 生成简单旋律: 主音-三音-五音循环
        sample_rate = 44100
        total_samples = sample_rate * duration_sec
        audio_data = np.array([], dtype=np.int16)
        
        # 简单三和弦循环
        chord_freqs = [freq, freq * 5/4, freq * 3/2]
        note_duration_ms = 500
        
        for i in range(int(duration_sec * 1000 / note_duration_ms)):
            note_freq = chord_freqs[i % len(chord_freqs)]
            note_data = generate_sine_wave(note_freq, note_duration_ms, sample_rate)
            audio_data = np.concatenate([audio_data, note_data])
        
        save_wav_file(filepath, audio_data[:total_samples], sample_rate)
        print(f"✓ {filename} - {description}")
    
    print(f"\n音乐占位符已生成至: {music_dir}")

if __name__ == "__main__":
    generate_sound_effects()
    generate_music_placeholder()
    print("\n" + "="*50)
    print("完成! 请在pubspec.yaml中声明这些资源文件")
    print("="*50)
