# Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-11-24
# Task: 创建统一的资源占位符生成脚本，支持批量生成和自动配置

<#
.SYNOPSIS
    四子游戏资源占位符生成工具（PowerShell版）

.DESCRIPTION
    自动生成开发测试所需的所有占位符资源，包括：
    - 应用图标（多尺寸）
    - 启动屏幕Logo
    - 静音音效文件
    - 静音音乐文件

.PARAMETER ResourceType
    资源类型：all（全部）、icon（图标）、audio（音频）

.PARAMETER Format
    音频格式：wav（默认）、mp3（需要FFmpeg）

.EXAMPLE
    .\generate_all_resources.ps1 -ResourceType all
    .\generate_all_resources.ps1 -ResourceType icon
    .\generate_all_resources.ps1 -ResourceType audio -Format mp3
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet('all', 'icon', 'audio')]
    [string]$ResourceType = 'all',
    
    [Parameter(Mandatory=$false)]
    [ValidateSet('wav', 'mp3')]
    [string]$Format = 'wav',
    
    [Parameter(Mandatory=$false)]
    [switch]$AutoConvert
)

# 颜色输出函数
function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Type = "Info"
    )
    
    switch ($Type) {
        "Success" { Write-Host $Message -ForegroundColor Green }
        "Warning" { Write-Host $Message -ForegroundColor Yellow }
        "Error" { Write-Host $Message -ForegroundColor Red }
        "Info" { Write-Host $Message -ForegroundColor Cyan }
        default { Write-Host $Message }
    }
}

# 检查Python环境
function Test-PythonAvailable {
    try {
        $pythonVersion = python --version 2>&1
        if ($pythonVersion -match "Python") {
            return $true
        }
    } catch {
        return $false
    }
    return $false
}

# 检查FFmpeg
function Test-FFmpegAvailable {
    try {
        $ffmpegVersion = ffmpeg -version 2>&1
        if ($ffmpegVersion -match "ffmpeg") {
            return $true
        }
    } catch {
        return $false
    }
    return $false
}

# 生成图标
function New-PlaceholderIcons {
    Write-ColorOutput "`n=== 生成占位图标 ===" "Info"
    
    if (-not (Test-PythonAvailable)) {
        Write-ColorOutput "Python未安装或未在PATH中" "Error"
        Write-ColorOutput "请访问 https://www.python.org/ 安装Python" "Warning"
        return $false
    }
    
    # 检查PIL库
    Write-ColorOutput "检查Pillow库..." "Info"
    $pipList = pip list 2>&1 | Out-String
    if ($pipList -notmatch "Pillow") {
        Write-ColorOutput "安装Pillow库..." "Info"
        pip install Pillow
    }
    
    # 运行Python脚本
    Write-ColorOutput "执行图标生成脚本..." "Info"
    python scripts/generate_placeholder_icon.py
    
    if ($LASTEXITCODE -eq 0) {
        Write-ColorOutput "图标生成成功！" "Success"
        
        # 提示配置flutter_launcher_icons
        Write-ColorOutput "`n下一步：配置Flutter图标" "Info"
        Write-ColorOutput "运行: flutter pub run flutter_launcher_icons" "Warning"
        
        return $true
    } else {
        Write-ColorOutput "图标生成失败" "Error"
        return $false
    }
}

# 生成音频
function New-PlaceholderAudio {
    Write-ColorOutput "`n=== 生成占位音频 ===" "Info"
    
    if (-not (Test-PythonAvailable)) {
        Write-ColorOutput "Python未安装或未在PATH中" "Error"
        return $false
    }
    
    # 运行Python脚本生成WAV
    Write-ColorOutput "执行音频生成脚本..." "Info"
    python scripts/generate_placeholder_audio.py
    
    if ($LASTEXITCODE -ne 0) {
        Write-ColorOutput "音频生成失败" "Error"
        return $false
    }
    
    # 如果需要MP3且FFmpeg可用
    if ($Format -eq 'mp3' -or $AutoConvert) {
        if (Test-FFmpegAvailable) {
            Write-ColorOutput "`n转换WAV到MP3..." "Info"
            Convert-WavToMp3
        } else {
            Write-ColorOutput "`nFFmpeg未安装，跳过MP3转换" "Warning"
            Write-ColorOutput "安装FFmpeg: choco install ffmpeg" "Info"
            Write-ColorOutput "或手动转换WAV文件" "Info"
        }
    }
    
    Write-ColorOutput "音频生成成功！" "Success"
    return $true
}

# WAV转MP3
function Convert-WavToMp3 {
    $wavFiles = Get-ChildItem -Path "assets\sounds" -Filter "*.wav" -Recurse
    
    if ($wavFiles.Count -eq 0) {
        Write-ColorOutput "未找到WAV文件" "Warning"
        return
    }
    
    Write-ColorOutput "找到 $($wavFiles.Count) 个WAV文件" "Info"
    
    $converted = 0
    foreach ($wavFile in $wavFiles) {
        $mp3File = $wavFile.FullName -replace '\.wav$', '.mp3'
        
        Write-Host "  转换: $($wavFile.Name) -> $([System.IO.Path]::GetFileName($mp3File))" -ForegroundColor Gray
        
        # FFmpeg转换命令
        $ffmpegArgs = @(
            "-i", $wavFile.FullName,
            "-q:a", "9",
            "-y",  # 覆盖已存在文件
            $mp3File
        )
        
        $process = Start-Process -FilePath "ffmpeg" -ArgumentList $ffmpegArgs -NoNewWindow -Wait -PassThru
        
        if ($process.ExitCode -eq 0) {
            $converted++
            # 删除WAV文件
            Remove-Item $wavFile.FullName -Force
        } else {
            Write-ColorOutput "  转换失败: $($wavFile.Name)" "Error"
        }
    }
    
    Write-ColorOutput "`n成功转换 $converted/$($wavFiles.Count) 个文件" "Success"
}

# 检查依赖
function Test-Dependencies {
    Write-ColorOutput "`n=== 检查依赖环境 ===" "Info"
    
    # 检查Python
    if (Test-PythonAvailable) {
        $pythonVersion = python --version 2>&1
        Write-ColorOutput "Python: $pythonVersion" "Success"
    } else {
        Write-ColorOutput "Python: 未安装" "Error"
    }
    
    # 检查FFmpeg
    if (Test-FFmpegAvailable) {
        $ffmpegVersion = (ffmpeg -version 2>&1 | Select-String "ffmpeg version").ToString()
        Write-ColorOutput "FFmpeg: $ffmpegVersion" "Success"
    } else {
        Write-ColorOutput "FFmpeg: 未安装（可选，用于MP3转换）" "Warning"
    }
    
    Write-ColorOutput ""
}

# 主函数
function Main {
    Write-ColorOutput "======================================" "Info"
    Write-ColorOutput "   四子游戏资源占位符生成工具" "Info"
    Write-ColorOutput "======================================" "Info"
    
    Test-Dependencies
    
    $success = $true
    
    switch ($ResourceType) {
        'all' {
            Write-ColorOutput "生成所有资源..." "Info"
            $iconResult = New-PlaceholderIcons
            $audioResult = New-PlaceholderAudio
            $success = $iconResult -and $audioResult
        }
        'icon' {
            $success = New-PlaceholderIcons
        }
        'audio' {
            $success = New-PlaceholderAudio
        }
    }
    
    Write-ColorOutput "`n======================================" "Info"
    if ($success) {
        Write-ColorOutput "✅ 资源生成完成！" "Success"
        Write-ColorOutput "`n⚠️  提醒：" "Warning"
        Write-ColorOutput "1. 这些是开发测试用的占位符资源" "Warning"
        Write-ColorOutput "2. 正式发布前必须替换为专业资源" "Warning"
        Write-ColorOutput "`n下一步操作：" "Info"
        Write-ColorOutput "flutter pub run flutter_launcher_icons" "Info"
        Write-ColorOutput "flutter pub run flutter_native_splash:create" "Info"
        Write-ColorOutput "flutter run" "Info"
    } else {
        Write-ColorOutput "❌ 资源生成失败" "Error"
        Write-ColorOutput "请检查错误信息并重试" "Error"
    }
    Write-ColorOutput "======================================" "Info"
}

# 执行主函数
Main
